function new_archived_transaction(){jQuery(document).trigger("new_archived_transaction");try{var a=Buleys.db.transaction(["archive"],IDBTransaction.READ_WRITE,5E3);a.oncomplete=function(){console.log("archive transaction complete");delete Buleys.objectStore};a.onabort=function(b){console.log("archive transaction aborted");console.log(b)};Buleys.objectStore=a.objectStore("archive")}catch(c){a=Buleys.db.setVersion(parseInt(Buleys.version,10));a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("archive",
{keyPath:"link"},true);Buleys.objectStore.createIndex("topic_slug","topic_slug",{unique:false});Buleys.objectStore.createIndex("topic_type","topic_type",{unique:false});Buleys.objectStore.createIndex("modified","modified",{unique:false});var b=Buleys.db.transaction(["archive"],IDBTransaction.READ_WRITE,5E3);b.oncomplete=function(){console.log("archive transaction complete");delete Buleys.objectStore};b.onabort=function(d){console.log("archive transaction aborted");console.log(d)};Buleys.objectStore=
b.objectStore("archive")};a.onerror=function(){}}}
function get_archived(a,c,b,d,g){jQuery(document).trigger("get_archived");console.log("archive.js > get_archived");if(typeof g=="undefined")g=false;typeof b=="undefined"||b==null||parseInt(b);typeof d=="undefined"||d==null?(new Date).getTime():parseInt(d);new_categories_transaction();Buleys.index=Buleys.objectStoreCategories.index("slug");a=IDBKeyRange.only(c);console.log(a);console.log("^key");a=Buleys.index.openCursor(a);a.onsuccess=function(h){h=h.target.result;var i=h.value;if(i){new_archived_transaction();
Buleys.objectStore.get(i.link).onsuccess=function(j){if(typeof j.target.result!=="undefined"&&g!==true){new_item_transaction();var e=Buleys.objectStore.get(j.target.result.link);e.onsuccess=function(f){if(typeof f.target.result!=="undefined")if(typeof f.target.result.link!=="undefined")if(jQuery("#"+f.target.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){console.log("get_item_raw");console.log(f.target.result);get_item_raw(f.target.result.link)}}}else if(g==true){new_item_transaction();e=
Buleys.objectStore.get(i.link);e.onsuccess=function(){typeof e.result!=="undefined"&&typeof e.result!=="undefined"&&jQuery("#"+i.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item_raw(e.result.link)}}};h["continue"]()}};a.onerror=function(){}}
function archive_item(a){jQuery(document).trigger("archive_item");console.log("Archiving item: "+a);new_archived_transaction();a={link:a,modified:(new Date).getTime()};var c=Buleys.objectStore.add(a);c.onsuccess=function(b){console.log(b.target.result);Buleys.objectId=c.result};c.onerror=function(b){console.log(b);console.log("error archiving item")}}
function check_if_item_is_archived(a){jQuery(document).trigger("check_if_item_is_archived");new_archived_transaction();var c=Buleys.objectStore.get(a);c.onsuccess=function(){checker=c;typeof c.result!="undefined"?jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("archived"):jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("unarchived")};c.onerror=function(){}}
function add_item_to_archives_database(a,c,b){jQuery(document).trigger("add_item_to_archives_database");new_archived_transaction();a={item_link:a,topic_slug:c,topic_type:b,modified:(new Date).getTime()};var d=Buleys.objectStore.add(a);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}
function unarchive_item(a){jQuery(document).trigger("unarchive_item");new_archived_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}function remove_item_from_archives_database(a){jQuery(document).trigger("remove_item_from_archives_database");new_archived_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}};
