function new_categories_transaction(){try{var a=Buleys.db.transaction(["categories"],1,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("categories")}catch(b){console.log("new_categories_transaction(): Could not open objectStore. You may have to create it first");a=0;if(Buleys.db.version>0)a=1;else a+=1;console.log(Buleys.db);a=Buleys.db.setVersion(a);a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("categories",{keyPath:"id"},
true);Buleys.objectStore.createIndex("link","link",{unique:false});Buleys.objectStore.createIndex("slug","slug",{unique:false});Buleys.objectStore.createIndex("type","type",{unique:false});Buleys.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function add_category_controls(a){jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .delete_category").remove();jQuery("#overlay .selected_category").removeClass(".selected_category");var b,e=jQuery(a).html(),c=jQuery(a).attr("link"),f=jQuery(a).attr("type"),d=jQuery(a).attr("slug");new_votes_transaction();var h=c.replace(/[^a-zA-Z0-9-_]+/g,"")+f.toLowerCase()+d.toLowerCase(),g=Buleys.objectStore.get(h);g.onsuccess=function(){if(typeof g.result==
"undefined"||g.result==""){b="<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+c+"' type='"+f+"' slug='"+d+"'></span>";b=b+""+e;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+c+"' type='"+f+"' slug='"+d+"'></div>";b=b+"<div class='vote_down_category empty_thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+d+"'></div>"}else if(typeof g.result!="undefined")if(g.result.vote_value==-1){b="<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+
c+"' type='"+f+"' slug='"+d+"'></span>";b=b+""+e;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+c+"' type='"+f+"' slug='"+d+"'></div>";b=b+"<div class='remove_category_down_vote thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+d+"'></div>"}else{b=g.result.vote_value==1?"<span class='remove_category_up_vote thumb_up_icon float_left category_hover_icon ' link='"+c+"' type='"+f+"' slug='"+d+"'></span>":"<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+
c+"' type='"+f+"' slug='"+d+"'></span>";b=b+""+e;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+c+"' type='"+f+"' slug='"+d+"'></div>";b=b+"<div class='vote_down_category empty_thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+d+"'></div>"}else{b="<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+c+"' type='"+f+"' slug='"+d+"'></span>";b=b+""+e;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+
c+"' type='"+f+"' slug='"+d+"'></div>";b=b+"<div class='vote_down_category empty_thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+d+"'></div>"}jQuery(a).html(b)};g.onerror=function(){}}function remove_category_for_item(a,b,e){new_categories_transaction();a=Buleys.objectStore["delete"](a+e+b);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function add_category_controls_without_vote_status(a){jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .delete_category").remove();jQuery("#overlay .selected_category").removeClass(".selected_category");var b=jQuery(a).html(),e=jQuery(a).attr("link"),c=jQuery(a).attr("type"),f=jQuery(a).attr("slug");jQuery(a).html("<div class='vote_block'>"+("<span class='vote_up_category thumb_up_icon float_left category_hover_icon ' link='"+e+"' type='"+
c+"' slug='"+f+"'></span>"+b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+e+"' type='"+c+"' slug='"+f+"'></div><div class='vote_down_category thumb_icon float_right category_hover_icon' link='"+e+"' type='"+c+"' slug='"+f+"'></div>")+"</div>")}function remove_category_for_item(a,b,e){new_categories_transaction();a=Buleys.objectStore["delete"](a+e+b);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function remove_item_from_categories_database(a){new_categories_transaction();Buleys.index=Buleys.objectStore.index("link");var b=Buleys.index.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined")if(typeof b.result!=="undefined"){var e="";e=b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")+b.result.slug.toLowerCase()+b.result.type.toLowerCase();new_categories_transaction();e=Buleys.objectStore["delete"](e);e.onsuccess=function(){delete Buleys.objectId};e.onerror=function(){}}else $.each(b.result,
function(c,f){var d="";d=f.link.replace(/[^a-zA-Z0-9-_]+/g,"")+f.slug.toLowerCase()+f.type.toLowerCase();new_categories_transaction();d=Buleys.objectStore["delete"](d);d.onsuccess=function(){delete Buleys.objectId};d.onerror=function(){}})};b.onerror=function(){}}
function add_categories_to_categories_database(a,b){jQuery.each(b,function(e,c){if(typeof c.key!=="undefined"&&c.key!==""&&c.key.toLowerCase()=="function"){new_categories_transaction();var f={id:a.replace(/[^a-zA-Z0-9-_]+/g,"")+c.key.toLowerCase()+c.type.toLowerCase(),link:a,slug:c.key,type:c.type,value:c.value,modified:(new Date).getTime()};f=Buleys.objectStore.add(f);f.onsuccess=function(){if(typeof c.key!=="undefined"){var d=c.type.toLowerCase()+"_"+c.key.toLowerCase();if(typeof Buleys.queues.new_items[d]==
"undefined")Buleys.queues.new_items[d]=0;Buleys.queues.new_items[d]+=1}};f.onerror=function(){}}})}
function get_item_categories_for_overlay(a){new_categories_transaction();Buleys.objectStore.get(a);try{new_categories_transaction();Buleys.index=Buleys.objectStore.index("link");var b=Buleys.index.getAll(a);b.onsuccess=function(){var c=b.result;c&&c.length>=0&&jQuery.each(c,function(f,d){if(jQuery("#categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).length<1){var h="<ul class='category_list' id='categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+"'></ul>";jQuery("#overlay_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).append(h)}h=
"<li id='list_item_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+d.type.toLowerCase()+d.slug.toLowerCase()+"' class='category_list_item' link='"+a+"' type='"+d.type.toLowerCase()+"' slug='"+d.slug.toLowerCase()+"'><a id='"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+d.type.toLowerCase()+d.slug.toLowerCase()+"'  class='category' link='"+a+"' type='"+d.type.toLowerCase()+"' slug='"+d.slug.toLowerCase()+"' href='/"+d.type.toLowerCase()+"/"+d.slug+"'>"+d.value+"</a></li>";jQuery("#categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,
"")).append(h);get_vote_info(a,d.type.toLowerCase(),d.slug.toLowerCase())})};request.onerror=function(){}}catch(e){}}$(".delete_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),e=$(this).attr("slug");$(this).parent().parent().remove();remove_category_for_item(a.replace(/[^a-zA-Z0-9-_]+/g,""),b,e);$(this).hasClass("voted")||post_feedback("delete_category",a,b,e)});
$(".vote_up_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),e=$(this).attr("slug"),c="";c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+e.toLowerCase();jQuery(this).removeClass("empty_thumb_up_icon").addClass("thumb_up_icon");jQuery(this).parent().children(".thumb_icon").removeClass(".thumb_icon").addClass("empty_thumb_icon");add_or_update_vote(c,1);$(this).hasClass("voted")||post_feedback("category_upvote",a,b,e);$(this).addClass("voted");
$(this).removeClass("vote_up_category");$(this).addClass("remove_category_up_vote")});
$(".vote_down_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),e=$(this).attr("slug"),c="";jQuery(this).removeClass("empty_thumb_icon").addClass("thumb_icon");jQuery(this).parent().children(".thumb_up_icon").removeClass(".thumb_up_icon").addClass("empty_thumb_up_icon");c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+e.toLowerCase();add_or_update_vote(c,-1);$(this).hasClass("voted")||post_feedback("category_downvote",a,b,e);$(this).addClass("voted");
$(this).removeClass("vote_down_category");$(this).addClass("remove_category_down_vote")});
$(".remove_category_up_vote").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),e=$(this).attr("slug"),c="";c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+e.toLowerCase();jQuery(this).removeClass("thumb_up_icon").addClass("empty_thumb_up_icon");remove_vote(c);$(this).hasClass("voted")&&post_feedback("remove_category_upvote",a,b,e);$(this).removeClass("voted");$(this).removeClass("remove_category_up_vote");$(this).addClass("vote_up_category")});
$(".remove_category_down_vote").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),e=$(this).attr("slug"),c="";jQuery(this).removeClass("thumb_icon").addClass("empty_thumb_icon");c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+e.toLowerCase();remove_vote(c);$(this).hasClass("voted")&&post_feedback("remove_category_downvote",a,b,e);$(this).removeClass("voted");$(this).removeClass("remove_category_down_vote");$(this).addClass("vote_down_category")});
$("#overlay .category").live("mouseenter",function(a){a.preventDefault();add_category_controls(jQuery(this))});$("#overlay .category").live("mouseleave",function(a){a.preventDefault();jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .remove_category_up_vote").remove();jQuery("#overlay .remove_category_down_vote").remove();jQuery("#overlay .delete_category").remove()});
