function new_categories_transaction(){try{var a=Buleys.db.transaction(["categories"],1,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("categories")}catch(c){console.log("new_categories_transaction(): Could not open objectStore. You may have to create it first");a=0;if(Buleys.db.version>0)a=1;else a+=1;console.log(Buleys.db);a=Buleys.db.setVersion(a);a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("categories",{keyPath:"id"},
true);Buleys.objectStore.createIndex("link","link",{unique:false});Buleys.objectStore.createIndex("slug","slug",{unique:false});Buleys.objectStore.createIndex("type","type",{unique:false});Buleys.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function add_category_controls(a){jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .delete_category").remove();jQuery("#overlay .selected_category").removeClass(".selected_category");var c=jQuery(a).html(),e=jQuery(a).attr("link"),d=jQuery(a).attr("type"),f=jQuery(a).attr("slug");jQuery(a).html("<span class='vote_up_category thumb_up_icon' link='"+e+"' type='"+d+"' slug='"+f+"'></span><span class='vote_down_category thumb_icon' link='"+
e+"' type='"+d+"' slug='"+f+"'></span>"+c+"<div class='delete_category close_icon' link='"+e+"' type='"+d+"' slug='"+f+"'></div>")}function remove_category_for_item(a,c,e){new_categories_transaction();a=Buleys.objectStore["delete"](a+e+c);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function remove_item_from_categories_database(a){new_categories_transaction();Buleys.index=Buleys.objectStore.index("link");var c=Buleys.index.get(a);c.onsuccess=function(){if(typeof c.result!=="undefined")if(typeof c.result!=="undefined"){var e="";e=c.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")+c.result.slug.toLowerCase()+c.result.type.toLowerCase();new_categories_transaction();e=Buleys.objectStore["delete"](e);e.onsuccess=function(){delete Buleys.objectId};e.onerror=function(){}}else $.each(c.result,
function(d,f){var b="";b=f.link.replace(/[^a-zA-Z0-9-_]+/g,"")+f.slug.toLowerCase()+f.type.toLowerCase();new_categories_transaction();b=Buleys.objectStore["delete"](b);b.onsuccess=function(){delete Buleys.objectId};b.onerror=function(){}})};c.onerror=function(){}}
function add_categories_to_categories_database(a,c){jQuery.each(c,function(e,d){if(typeof d.key!=="undefined"){new_categories_transaction();var f={id:a.replace(/[^a-zA-Z0-9-_]+/g,"")+d.key.toLowerCase()+d.type.toLowerCase(),link:a,slug:d.key,type:d.type,value:d.value,modified:(new Date).getTime()};f=Buleys.objectStore.add(f);f.onsuccess=function(){if(typeof d.key!=="undefined"){var b=d.type.toLowerCase()+"_"+d.key.toLowerCase();if(typeof Buleys.queues.new_items[b]=="undefined")Buleys.queues.new_items[b]=
0;Buleys.queues.new_items[b]+=1}};f.onerror=function(){}}})}
function get_item_categories_for_overlay(a){new_categories_transaction();Buleys.objectStore.get(a);try{new_categories_transaction();Buleys.index=Buleys.objectStore.index("link");var c=Buleys.index.getAll(a);c.onsuccess=function(){var d=c.result;d&&d.length>=0&&jQuery.each(d,function(f,b){if(jQuery("#categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).length<1){var g="<ul class='category_list' id='categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+"'></ul>";jQuery("#overlay_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).append(g)}g=
"<li id='list_item_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.type.toLowerCase()+b.slug.toLowerCase()+"' class='category_list_item' link='"+a+"' type='"+b.type.toLowerCase()+"' slug='"+b.slug.toLowerCase()+"'><a id='"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.type.toLowerCase()+b.slug.toLowerCase()+"'  class='category' link='"+a+"' type='"+b.type.toLowerCase()+"' slug='"+b.slug.toLowerCase()+"' href='/"+b.type.toLowerCase()+"/"+b.slug+"'>"+b.value+"</a></li>";jQuery("#categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,
"")).append(g);get_vote_info(a,b.type.toLowerCase(),b.slug.toLowerCase())})};request.onerror=function(){}}catch(e){}};
