function new_favorite_transaction(){try{var a=Buleys.db.transaction(["favorites"],1,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("favorites")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.db.version)+1);a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("favorites",{keyPath:"item_link"},true);Buleys.objectStore.createIndex("topic_slug","topic_slug",{unique:false});Buleys.objectStore.createIndex("topic_type","topic_type",
{unique:false});Buleys.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function add_favorite_to_results(a){var b=a.link.replace(/[^a-zA-Z0-9-_]+/g,"");jQuery("#"+b).length||jQuery("<li class='item' modified= '"+a.modified+"'  index-date= '"+a.index_date+"' published-date= '"+a.published_date+"' id='"+a.link.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+a.link+"'>"+a.title+"</a><div class='magnify_icon'></div></li>").hide().prependTo("#results").fadeIn("slow")}
function get_favorites(a,b,c,e){typeof c=="undefined"||parseInt(c);typeof e=="undefined"?(new Date).getTime():parseInt(e);new_categories_transaction();Buleys.index=Buleys.objectStore.index("slug");var h=Buleys.index.getAll(b);h.onsuccess=function(){var f=h.result;if(f)f.length>1?jQuery.each(f,function(j,d){new_favorite_transaction();var i=Buleys.objectStore.get(d.link);i.onsuccess=function(){if(typeof i.result!=="undefined"){new_item_transaction();var g=Buleys.objectStore.get(d.link);g.onsuccess=
function(){typeof g.result!=="undefined"&&typeof g.result.link!=="undefined"&&jQuery("#"+d.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item_raw(g.result.link)}}};i.onerror=function(){if(jQuery("#"+d.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(d);check_if_item_is_favorited(d.link);check_if_item_is_read(d.link);check_if_item_is_seen(d.link)}}}):get_item(f.link)};h.onerror=function(){}}
function get_favorite(a){if(typeof a!=="undefined"){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"){new_archived_transaction();var c=Buleys.objectStore.get(a);c.onsuccess=function(){if(typeof c.result==="undefined")if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_favorite_to_results(b.result);check_if_favorite_is_favorited(b.result.link);check_if_favorite_is_read(b.result.link);check_if_favorite_is_seen(b.result.link)}};
c.onerror=function(){if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_favorite_to_results(b.result);check_if_favorite_is_favorited(b.result.link);check_if_favorite_is_read(b.result.link);check_if_favorite_is_seen(b.result.link)}}}};b.onerror=function(){}}}
function get_favorite_for_console(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"&&typeof b.result.id=="string"){var c="<div id='console_"+b.result.id.replace(/[^a-zA-Z0-9-_]+/g,"")+"'>";c=c+"<h3><a href='"+b.result.id+"'>"+b.result.title+"</a></h3>";c=c+"<p>"+b.result.author+"</p>";c+="</div>";send_to_console(c)}};b.onerror=function(){}}
function get_favorite_for_overlay(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"&&typeof b.result.link=="string"){var c='<div id="overlay_right"><div class="sidebar_close_link"><div href="#" class="close_sidebar_link close_icon" id="'+favorite_slug+"\"></div></div><h3 id='overlay_"+favorite_slug.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><div href='"+b.result.link+"'>"+b.result.title+"</div></h3></div><div id='overlay_left'></div>";send_to_overlay(c)}};
b.onerror=function(){}}function add_item_as_favorite(a){new_status_transaction();a={link:a,status:"favorite",modified:(new Date).getTime()};var b=Buleys.objectStore.add(a);b.onsuccess=function(){Buleys.objectId=b.result};b.onerror=function(){}}
function check_if_item_is_favorited_for_overlay(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"){jQuery("#overlay_left").prepend("<div class='overlay_favorite_status' id='favorite_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><div href='"+a+"' class='unfav_link star_icon'></div></div>");jQuery("#overlay_left").addClass("favorited")}else{jQuery("#overlay_left").prepend("<div class='overlay_favorite_status' id='favorite_"+a.replace(/[^a-zA-Z0-9-_]+/g,
"")+"'><div href='"+a+"' class='fav_link empty_star_icon'></div></div>");jQuery("#overlay_left").addClass("unfavorited")}};b.onerror=function(){}}
function check_if_item_is_favorited(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"){Buleys.settings.show_favorite_status!==false&&jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).prepend("<span class='favorite_status'><div href='"+a+"' class='unfav_link star_icon'></div></span>");jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("favorited")}else{Buleys.settings.show_favorite_status!==false&&jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,
"")).prepend("<span class='favorite_status'><div href='"+a+"' class='fav_link empty_star_icon'></div></span>");jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("unfavorited")}};b.onerror=function(){}}function add_item_to_favorites_database(a,b,c){new_favorite_transaction();a={item_link:a,topic_slug:b,topic_type:c,modified:(new Date).getTime()};var e=Buleys.objectStore.add(a);e.onsuccess=function(){Buleys.objectId=e.result};e.onerror=function(){}}
function remove_item_from_favorites_database(a){new_favorite_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
$(".unfav_link").live("click",function(a){a.preventDefault();console.log(jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children(".unfav_link"));jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("star_icon").addClass("empty_star_icon");jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");
jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children(".unfav_link").removeClass("unfav_link").addClass("fav_link");jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");if(typeof Buleys.view.page!==
"undefined"&&(Buleys.view.type=="favorites"||Buleys.view.page=="favorites"||Buleys.view.page=="favs"))jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).remove();remove_item_from_favorites_database($(this).attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("unstar",$(this).attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item removed from favorites</p>");setTimeout("fade_console_message()",1E3)});
$("#favorite").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("unfav_link");
jQuery("#favorite_"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(".cursor a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",$(".cursor a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item favorited</p>");
setTimeout("fade_console_message()",1E3)}else $.each($(".selected"),function(b,c){jQuery("#"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,
"")).children(".favorite_status").children("div").removeClass("unfav_link");jQuery("#favorite_"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(c).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",
$(c).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item favorited</p>");setTimeout("fade_console_message()",1E3)})});
$("#unfavorite").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("star_icon").addClass("empty_star_icon");jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("unfav_link");
jQuery("#favorite_"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");if(typeof Buleys.view.type!=="undefined"&&(Buleys.view.type=="favorites"||Buleys.view.page=="favorites"||Buleys.view.page=="favs"))jQuery("#"+$(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,
"")).remove();remove_item_from_favorites_database($(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("unstar",$(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item removed from favorites</p>");setTimeout("fade_console_message()",1E3)}else $.each($(".selected"),function(b,c){jQuery("#"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("star_icon").addClass("empty_star_icon");
jQuery("#"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("unfav_link");jQuery("#favorite_"+jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+
jQuery(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");if(typeof Buleys.view.type!=="undefined"&&(Buleys.view.type=="favorites"||Buleys.view.page=="favorites"||Buleys.view.page=="favs"))jQuery("#"+$(c).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).remove();remove_item_from_favorites_database($(c).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("unstar",$(c).children("a").attr("href"),
Buleys.view.slug,Buleys.view.type);send_to_console("<p>item removed from favorites</p>");setTimeout("fade_console_message()",1E3)})});
$(".fav_link").live("click",function(a){a.preventDefault();jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("fav_link").addClass("unfav_link");
jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(this).attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",$(this).attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item favorited</p>");
setTimeout("fade_console_message()",1E3)});$("#select_favorites").live("click",function(a){a.preventDefault();$.each($(".favorited"),function(b,c){if(!jQuery(c).hasClass("selected")){jQuery(c).addClass("selected");jQuery(c).attr("status",jQuery(c).attr("status")+" selected")}})});$("#deselect_favorites").live("click",function(a){a.preventDefault();$.each($(".favorited"),function(b,c){jQuery(c).removeClass("selected");jQuery(c).attr("status",jQuery(c).attr("status").replace(" selected",""))})});
