function new_favorite_transaction(){try{var a=Buleys.db.transaction(["favorites"],1,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("favorites")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.db.version)+1);a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("favorites",{keyPath:"item_link"},true);Buleys.objectStore.createIndex("topic_slug","topic_slug",{unique:false});Buleys.objectStore.createIndex("topic_type","topic_type",
{unique:false});Buleys.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function add_favorite_to_results(a){var b=a.link.replace(/[^a-zA-Z0-9-_]+/g,"");jQuery("#"+b).length||jQuery("<li class='item' modified= '"+a.modified+"'  index-date= '"+a.index_date+"' published-date= '"+a.published_date+"' id='"+a.link.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+a.link+"'>"+a.title+"</a><a class='examine_item' href='http://buleys.com/images/icons/fugue-shadowless/magnifier.png'></a></li>").hide().prependTo("#results").fadeIn("slow")}
function get_favorites(a,b,c,e){typeof c=="undefined"||parseInt(c);typeof e=="undefined"?(new Date).getTime():parseInt(e);new_categories_transaction();Buleys.index=Buleys.objectStore.index("slug");var h=Buleys.index.getAll(b);h.onsuccess=function(){var f=h.result;if(f)f.length>1?jQuery.each(f,function(j,d){new_favorite_transaction();var i=Buleys.objectStore.get(d.link);i.onsuccess=function(){if(typeof i.result!=="undefined"){new_item_transaction();var g=Buleys.objectStore.get(d.link);g.onsuccess=
function(){typeof g.result!=="undefined"&&typeof g.result.link!=="undefined"&&jQuery("#"+d.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item_raw(g.result.link)}}};i.onerror=function(){if(jQuery("#"+d.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(d);check_if_item_is_favorited(d.link);check_if_item_is_read(d.link);check_if_item_is_seen(d.link)}}}):get_item(f.link)};h.onerror=function(){}}
function get_favorite(a){if(typeof a!=="undefined"){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"){new_archived_transaction();var c=Buleys.objectStore.get(a);c.onsuccess=function(){if(typeof c.result==="undefined")if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_favorite_to_results(b.result);check_if_favorite_is_favorited(b.result.link);check_if_favorite_is_read(b.result.link);check_if_favorite_is_seen(b.result.link)}};
c.onerror=function(){if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_favorite_to_results(b.result);check_if_favorite_is_favorited(b.result.link);check_if_favorite_is_read(b.result.link);check_if_favorite_is_seen(b.result.link)}}}};b.onerror=function(){}}}
function get_favorite_for_console(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"&&typeof b.result.id=="string"){var c="<div id='console_"+b.result.id.replace(/[^a-zA-Z0-9-_]+/g,"")+"'>";c=c+"<h3><a href='"+b.result.id+"'>"+b.result.title+"</a></h3>";c=c+"<p>"+b.result.author+"</p>";c+="</div>";send_to_console(c)}};b.onerror=function(){}}
function get_favorite_for_overlay(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!="undefined"&&typeof b.result.link=="string"){var c='<div id="overlay_right"><div class="sidebar_close_link"><a href="#" class="close_sidebar_link" id="'+favorite_slug+'"><img src="/images/icons/fugue-shadowless/cross-button.png"></a></div><h3 id=\'overlay_'+favorite_slug.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+b.result.link+"'>"+b.result.title+"</a></h3></div><div id='overlay_left'></div>";
send_to_overlay(c)}};b.onerror=function(){}}function add_item_as_favorite(a){new_status_transaction();a={link:a,status:"favorite",modified:(new Date).getTime()};var b=Buleys.objectStore.add(a);b.onsuccess=function(){Buleys.objectId=b.result};b.onerror=function(){}}
function check_if_item_is_favorited_for_overlay(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){checker=b;if(typeof b.result!="undefined"){jQuery("#overlay_left").prepend("<span class='overlay_favorite_status' id='favorite_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+a+"' class='unfav_link'><img src='http://buleys.com/images/icons/fugue-shadowless/star.png'></a></span>");jQuery("#overlay_left").addClass("favorited")}else{jQuery("#overlay_left").prepend("<span class='overlay_favorite_status' id='favorite_"+
a.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+a+"' class='fav_link'><img src='http://buleys.com/images/icons/fugue-shadowless/star-empty.png'></a></span>");jQuery("#overlay_left").addClass("unfavorited")}};b.onerror=function(){}}
function check_if_item_is_favorited(a){new_favorite_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){checker=b;if(typeof b.result!="undefined"){jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).prepend("<span class='favorite_status'><a href='"+a+"' class='unfav_link'><img src='http://buleys.com/images/icons/fugue-shadowless/star.png'></a></span>");jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("favorited")}else{jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).prepend("<span class='favorite_status'><a href='"+
a+"' class='fav_link'><img src='http://buleys.com/images/icons/fugue-shadowless/star-empty.png'></a></span>");jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("unfavorited")}};b.onerror=function(){}}function add_item_to_favorites_database(a,b,c){new_favorite_transaction();a={item_link:a,topic_slug:b,topic_type:c,modified:(new Date).getTime()};var e=Buleys.objectStore.add(a);e.onsuccess=function(){Buleys.objectId=e.result};e.onerror=function(){}}
function remove_item_from_favorites_database(a){new_favorite_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}};
