function temporarily_disable_hotkeys(){}function disable_hotkeys(){Buleys.settings.hotkeys.disabled=true}function enable_hotkeys(){delete Buleys.settings.hotkeys.disabled}$("#show_commands").live("click",function(a){a.preventDefault();$("#result_controls").show()});$("#hide_commands").live("click",function(a){a.preventDefault();$("#result_controls").hide()});$("#show_button").live("click",function(){send_notification_to_desktop()});
$("html").live("keyup",function(a){if(typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled==="undefined"||typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled!=="undefined"&&Buleys.settings.hotkeys.disabled!==true)if(a.keyCode==68)Buleys.shortcuts.d_depressed=false;else if(a.keyCode==83)Buleys.shortcuts.s_depressed=false;else if(a.keyCode==16)Buleys.shortcuts.shift_depressed=
false;else if(a.keyCode==72)Buleys.shortcuts.s_depressed||Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$("#view_index").click():$("#close_item_preview").click());else if(a.keyCode==76){if(!Buleys.shortcuts.s_depressed)if(!Buleys.shortcuts.d_depressed)if(Buleys.shortcuts.shift_depressed)$("#view_home").click();else{$("#preview_item").click();jQuery(".cursor")}}else if(a.keyCode==78){$("#preview_item").click();jQuery(".selected").length>0?jQuery("#results li.selected:first").addClass("cursor"):
jQuery("#results li:first").addClass("cursor")}else if(a.keyCode==74)if(jQuery(".cursor").next().length>0)jQuery(".cursor").removeClass("cursor").next().addClass("cursor");else{jQuery(".cursor").removeClass("cursor");jQuery("#results li:first").addClass("cursor")}else if(a.keyCode==75)if(jQuery(".cursor").prev().length>0)jQuery(".cursor").removeClass("cursor").prev().addClass("cursor");else{jQuery(".cursor").removeClass("cursor");jQuery("#results li:last").addClass("cursor")}else if(a.keyCode==27){jQuery(".cursor").removeClass("cursor");
$("#close_all").click()}else if(a.keyCode==77)jQuery(".cursor").removeClass("cursor");else if(a.keyCode==219)$("#preview_item").click();else if(a.keyCode==221)$("#close_item_preview").click();else if(a.keyCode==89)$("#show_commands").click();else if(a.keyCode==85)$("#hide_commands").click();else if(a.keyCode==65)if(Buleys.shortcuts.s_depressed)$("#select_all").click();else Buleys.shortcuts.d_depressed&&$("#select_none").click();else if(a.keyCode==82)if(Buleys.shortcuts.s_depressed)$("#select_unread").click();
else if(Buleys.shortcuts.d_depressed)$("#deselect_unread").click();else Buleys.shortcuts.shift_depressed?$("#view_unread").click():$("#mark_unread").click();else if(a.keyCode!=13)if(a.keyCode==73)$("#select").click();else if(a.keyCode==79)$("#deselect").click();else if(a.keyCode==69)if(Buleys.shortcuts.s_depressed)$("#select_read").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_read").click();else Buleys.shortcuts.shift_depressed?$("#view_read").click():$("#mark_read").click();else if(a.keyCode==
88)if(Buleys.shortcuts.s_depressed)$("#select_none").click();else Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$("#view_trash").click():$("#delete").click());else if(a.keyCode==67)if(Buleys.shortcuts.s_depressed)$("#select_archived").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_archived").click();else Buleys.shortcuts.shift_depressed?$("#view_archive").click():$("#archive").click();else if(a.keyCode==86)if(Buleys.shortcuts.s_depressed)$("#select_unarchived").click();
else Buleys.shortcuts.d_depressed?$("#deselect_unarchived").click():$("#unarchive").click();else if(a.keyCode==70)if(Buleys.shortcuts.s_depressed)$("#select_favorites").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_favorites").click();else Buleys.shortcuts.shift_depressed?$("#view_favorites").click():$("#favorite").click();else if(a.keyCode==71)if(Buleys.shortcuts.s_depressed)$("#select_unfavorite").click();else Buleys.shortcuts.d_depressed?$("#deselect_unfavorite").click():$("#unfavorite").click();
else if(a.keyCode==81)if(Buleys.shortcuts.s_depressed)$("#select_seen").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_seen").click();else Buleys.shortcuts.shift_depressed?$("#view_seen").click():$("#mark_seen").click();else if(a.keyCode==87)if(Buleys.shortcuts.s_depressed)$("#select_unseen").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_unseen").click();else Buleys.shortcuts.shift_depressed?$("#view_unseen").click():$("#mark_unseen").click();else if(a.keyCode==90)if(Buleys.shortcuts.s_depressed)$("#select_inverse").click();
else Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$("#view_index").click():$("#refresh").click());else if(a.keyCode==73)$("#deselect").click();else a.keyCode==79&&$("#select").click()});
$("html").live("keydown",function(a){if(typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled==="undefined"||typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled!=="undefined"&&Buleys.settings.hotkeys.disabled!==true)if(a.keyCode==68)Buleys.shortcuts.d_depressed=true;else if(a.keyCode==83)Buleys.shortcuts.s_depressed=true;else if(a.keyCode==16)Buleys.shortcuts.shift_depressed=
true});
