function new_item_transaction(){try{var a=Buleys.db.transaction(["items"],1,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("items")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.db.version,10)+1);a.onsuccess=function(){Buleys.db.objectStore=Buleys.db.createObjectStore("items",{keyPath:"link"},false);Buleys.db.objectStore.createIndex("author","author",{unique:false});Buleys.db.objectStore.createIndex("published_date","published_date",
{unique:false});Buleys.db.objectStore.createIndex("index_date","index_date",{unique:false});Buleys.db.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function new_item_transaction_old(){try{var a=Buleys.db.transaction(["items"],1,1E3);a.oncomplete=function(){};a.onabort=function(){};Buleys.db.objectStore=a.objectStore("items");console.log("New Transaction",Buleys.db.objectStore)}catch(b){console.log("e",b);console.log("new_item_transaction(): Create object store; db: "+Buleys.db);console.log("Fail!",Buleys.db,typeof Buleys.db.setVersion);if(typeof Buleys.db.setVersion==="function"){a=Buleys.db.setVersion(parseInt(Buleys.db.version,10)+1);a.onsuccess=
function(){console.log("Version changed to ",Buleys.db.version,", so trying to create a database now.");Buleys.db.objectStore=Buleys.db.createObjectStore("items",{keyPath:"link"},false);Buleys.db.objectStore.createIndex("author","author",{unique:false});Buleys.db.objectStore.createIndex("published_date","published_date",{unique:false});Buleys.db.objectStore.createIndex("index_date","index_date",{unique:false});Buleys.db.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}}
function remove_item_from_items_database(a){new_item_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}function get_data_object_for_item(a){return{link:a.link,title:a.title,author:a.author,published_date:(new Date(a.published_date)).getTime(),index_date:(new Date(a.index_date)).getTime(),modified:(new Date).getTime()}}
function add_item_to_results(a){var b=a.link.replace(/[^a-zA-Z0-9-_]+/g,"");jQuery("#"+b).length||jQuery("<li class='item' modified= '"+a.modified+"'  index-date= '"+a.index_date+"' published-date= '"+a.published_date+"' id='"+a.link.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+a.link+"'>"+a.title+"</a><a class='examine_item' href='http://buleys.com/images/icons/fugue-shadowless/magnifier.png'></a></li>").hide().prependTo("#results").fadeIn("slow")}
function add_item_to_items_database(a){var b=get_data_object_for_item(a);new_deleted_transaction();var c=Buleys.objectStore.get(a.link);c.onsuccess=function(){if(typeof c.result==="undefined"){new_item_transaction();var d=Buleys.objectStore.add(b);d.onsuccess=function(){if(a.categories.length>1&&typeof a.categories.type==="undefined"&&typeof a.categories.key==="undefined")$.each(a.categories,function(f,e){if(Buleys.view.type==="home"||typeof Buleys.view.slug==="undefined"||typeof Buleys.view.slug===
""||e.key!==null&&typeof e.key!=="null"&&e.key===slug)if(typeof page==="undefined"||page!=="favorites"&&page!=="seen"&&page!=="read"&&page!=="archive")add_item_to_results(get_data_object_for_item(a))});else if(a.categories.length===1&&typeof a.categories.key!=="undefined")if(Buleys.view.type==="home"||a.categories[0].key.toLowerCase()===slug&&a.categories[0].type.toLowerCase()===type)add_item_to_results(get_data_object_for_item(a))};d.onerror=function(){}}};c.onerror=function(){}}
function check_if_item_is_read(a){new_status_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){typeof b.result!=="undefined"?jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("read"):jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("unread")};b.onerror=function(){}}
function get_item_for_overlay(a){new_item_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined"&&typeof b.result.link==="string"){var c='<div id="overlay_right"><div class="sidebar_close_link"><a href="#" class="close_sidebar_link" id="'+a+'"><img src="/images/icons/fugue-shadowless/cross-button.png"></a></div><h3 id=\'overlay_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+b.result.link+"'>"+b.result.title+"</a></h3></div><div id='overlay_left'></div><div id='overlay_controls'><a href='"+
a+"' class='favorite_item'>Favorite</a>&nbsp;<a href='"+a+"' class='unfavorite_item'>Unfavorite</a>&nbsp;<a href='"+a+"' class='mark_item_as_read'>Mark as read</a>&nbsp;<a href='"+a+"' class='mark_item_as_unread'>Mark as unread</a>&nbsp;<a href='"+a+"' class='mark_item_as_seen'>Mark as seen</a>&nbsp;<a href='"+a+"' class='mark_item_as_unseen'>Mark as unseen</a>&nbsp;<a href='"+a+"' class='archive_item'>Archive</a>&nbsp;<a href='"+a+"' class='delete_item'>Delete</a>&nbsp;<a href='"+a+"' class='unarchive_item'>Unarchive</a>&nbsp;<a href='"+
a+"' class='vote_item_up'>Vote up</a>&nbsp;<a href='"+a+"' class='vote_item_down'>Vote down</a>&nbsp;<a href='"+a+"' class='close_item_preview'>Close preview</a></div>";send_to_overlay(c)}};b.onerror=function(){}}
function get_item_raw_no_trash(a){if(typeof a!=="undefined"){new_item_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined")if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(b.result);check_if_item_is_favorited(b.result.link);check_if_item_is_read(b.result.link);check_if_item_is_seen(b.result.link)}};b.onerror=function(){if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(b.result);
check_if_item_is_favorited(b.result.link);check_if_item_is_read(b.result.link);check_if_item_is_seen(b.result.link)}}}}
function get_item(a){if(typeof a!=="undefined"){new_deleted_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result==="undefined"){new_item_transaction();var c=Buleys.objectStore.get(a);c.onsuccess=function(){if(typeof c.result!=="undefined"){new_archived_transaction();var d=Buleys.objectStore.get(a);d.onsuccess=function(){typeof d.result==="undefined"&&get_item_raw_no_trash(c.result.link)};d.onerror=function(){if(jQuery("#"+c.result.link.replace(/[^a-zA-Z0-9-_]+/g,
"")).length<=0){add_item_to_results(c.result);check_if_item_is_favorited(c.result.link);check_if_item_is_read(c.result.link);check_if_item_is_seen(c.result.link)}}}};c.onerror=function(){}}};b.onerror=function(){}}}
function get_item_raw(a){if(typeof a!=="undefined"){new_item_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined"){new_deleted_transaction();var c=Buleys.objectStore.get(a);c.onsuccess=function(){if(typeof c.result==="undefined")if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(b.result);check_if_item_is_favorited(b.result.link);check_if_item_is_read(b.result.link);check_if_item_is_seen(b.result.link)}}}};b.onerror=
function(){}}}
function get_items(a,b,c,d){var f=0;f=typeof c==="undefined"?0:parseInt(c,10);c=0;c=typeof d==="undefined"?(new Date).getTime():parseInt(d,10);if(typeof b==="undefined"||a==="home"){Buleys.keyRange=new IDBKeyRange.bound(f,c,true,false);console.log("Range Defined",Buleys.db,Buleys.keyRange);Buleys.db.onCursor=function(g){console.log("get_items callback objectStore",g,Buleys.db.objectStore);new_item_transaction();Buleys.db.indexItem=Buleys.db.objectStore.index("published_date");var h=Buleys.db.indexItem.openCursor(Buleys.keyRange);
h.onsuccess=function(){if(typeof h.result!=="undefined"){Buleys.cursor=h.result;console.log("get_items() cursor value ",Buleys.cursor.value);alert(Buleys.cursor.value.link);get_item(Buleys.cursor.value.link);if(typeof Buleys.cursor["continue"]==="function")Buleys.cursor["continue"]()}};h.onerror=function(){}};Buleys.db.onCursor(function(){})}else{new_categories_transaction();Buleys.index=Buleys.objectStore.index("slug");console.log("get_items db stuff ",Buleys.db,Buleys.index);var e=Buleys.index.getAll(b);
e.onsuccess=function(){var g=e.result;if(g)g.length>1?jQuery.each(g,function(h,i){console.log("get_item(): ",i.link);get_item(i.link)}):get_item(g.link)};e.onerror=function(){}}}
function get_item_for_console(a){new_item_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined"&&typeof b.result.id==="string"){var c="<div id='console_"+b.result.id.replace(/[^a-zA-Z0-9-_]+/g,"")+"'>";c=c+"<h3><a href='"+b.result.id+"'>"+b.result.title+"</a></h3>";c=c+"<p>"+b.result.author+"</p>";c+="</div>";send_to_console(c)}};b.onerror=function(){}}
function fire_off_request(){$.ajax({url:typeof Buleys.view.type==="undefined"||Buleys.view.type===""?"/feedback/index.php":"http://static.buleys.com/js/collections/"+Buleys.view.type+"/"+Buleys.view.slug+".js",dataType:"jsonp",jsonpCallback:"load_collection",error:function(){$("#index").html("<li class='item'>No results.</li>")},success:function(a){Buleys.view.slug=a.info.key;Buleys.view.type=a.info.type;populate_and_maybe_setup_indexeddbs(a.items);get_data_for_items(a.items);add_items(a.items,a.info.type,
a.info.key);load_page_title_info(a.info);add_or_update_topic(a.info.type+"_"+a.info.key,a.info)}})}function get_data_for_items(a){$.each(a,function(b,c){get_item(c.link)})}function add_items(a,b,c){$.each(a,function(d,f){add_item_if_new(f,b,c)})}function populate_and_maybe_setup_indexeddbs(a){$.each(a,function(b,c){add_item_if_doesnt_exist(c)})}
function add_item_if_new(a,b,c){new_item_transaction();var d=Buleys.objectStore.get(a.link);d.onsuccess=function(f){if(typeof f.target.result==="undefined"){new_deleted_transaction();Buleys.objectStore.get(a.link).onsuccess=function(e){if(typeof e.target.result==="undefined"){add_item_to_items_database(a);add_categories_to_categories_database(a.link,a.categories);send_to_console("<p>Added: <a href='"+a.link+"'>"+a.title+"</a></p>");e=b.toLowerCase()+"_"+c.toLowerCase();if(typeof Buleys.queues.new_items[e]===
"undefined")Buleys.queues.new_items[e]=0;Buleys.queues.new_items[e]+=1}};d.onerror=function(){}}};d.onerror=function(){}}function add_item_if_doesnt_exist_old(a){new_item_transaction();var b=Buleys.objectStore.get(a.link);b.onsuccess=function(){if(typeof b.result==="undefined"){add_item_to_items_database(a);add_categories_to_categories_database(a.link,a.categories)}};b.onerror=function(){}}
function add_item_if_doesnt_exist(a){new_item_transaction();var b=Buleys.objectStore.get(a.link);b.onsuccess=function(){if(typeof b.result==="undefined"){add_item_to_items_database(a);add_categories_to_categories_database(a.link,a.categories);a.categories.length>0&&$.each(a.categories,function(c,d){if(Buleys.view.type==="home"||typeof Buleys.view.slug==="undefined"||typeof Buleys.view.slug===""||d.key!==null&&typeof d.key!=="null"&&d.key===Buleys.view.slug&&d.type===Buleys.view.type){add_item_to_results(get_data_object_for_item(a));
check_if_item_is_favorited(a.link);check_if_item_is_read(a.link);check_if_item_is_seen(a.link)}})}};b.onerror=function(){}};
