$(document).bind("view_seen",function(b){b.preventDefault();console.log(location.pathname);console.log("view_seen clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c=typeof Buleys.view.page!="undefined"&&Buleys.view.page!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/seen":typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/seen":"http://www.buleys.com/seen";
history.pushState(b,"view_seen",c);reload_results()});
$(document).bind("view_unseen",function(b){b.preventDefault();console.log(location.pathname);console.log("view_unseen clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c=typeof Buleys.view.page!="undefined"&&Buleys.view.page!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/unseen":typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/unseen":"http://www.buleys.com/unseen";
history.pushState(b,"view_unseen",c);reload_results()});
$(document).bind("view_read",function(b){b.preventDefault();console.log(location.pathname);console.log("view_read clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c=typeof Buleys.view.page!="undefined"&&Buleys.view.page!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/read":typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/read":"http://www.buleys.com/read";
history.pushState(b,"view_read",c);reload_results()});
$(document).bind("view_unread",function(b){b.preventDefault();console.log(location.pathname);console.log("view_unread clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c=typeof Buleys.view.page!="undefined"&&Buleys.view.page!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/unread":typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/unread":"http://www.buleys.com/unread";
history.pushState(b,"view_unread",c);reload_results()});
$(document).bind("view_trash",function(b){b.preventDefault();console.log(location.pathname);console.log("view_trash clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c=typeof Buleys.view.page!="undefined"&&Buleys.view.page!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/trash":typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/trash":"http://www.buleys.com/trash";
history.pushState(b,"view_trash",c);reload_results()});
$(document).bind("view_archive",function(b){b.preventDefault();console.log(location.pathname);console.log("view_archive clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c=typeof Buleys.view.page!="undefined"&&Buleys.view.page!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/archive":typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/archive":
"http://www.buleys.com/archive";history.pushState(b,"view_archive",c);reload_results()});
$(document).bind("view_index",function(b){b.preventDefault();console.log(location.pathname);console.log("view_index clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";if(typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!="")c="http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/";else if(typeof Buleys.view.type!="undefined"&&Buleys.view.type!="")c="http://www.buleys.com/"+Buleys.view.type+"/";history.pushState(b,"view_index",
c);reload_results()});$(document).bind("view_home",function(b){b.preventDefault();console.log(location.pathname);console.log("view_home clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c="http://www.buleys.com/"+Buleys.view.type+"/";history.pushState(b,"view_home",c);reload_results()});
$(document).bind("view_settings",function(b){b.preventDefault();console.log(location.pathname);console.log("view_home clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};history.pushState(b,"view_settings","http://www.buleys.com/settings/");reload_results()});$(".close_item_preview").live("click",function(b){b.preventDefault();jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});
$(".sidebar_close_link").live("click",function(b){b.preventDefault();jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});$(document).bind("close_all",function(b){b.preventDefault();jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});
$(".mark_item_as_unread").live("click",function(b){b.preventDefault();$(this).removeClass("empty_star_icon").addClass("star_icon");$(this).removeClass("unfav_link");$(this).addClass("fav_link");b=jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));if(b.hasClass("read")){b.removeClass("read");b.addClass("unread")}remove_item_from_read_database($(this).attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>marked as unread</p>");setTimeout("fade_console_message()",1E3)});
$(document).bind("mark_all_items_as_read",function(b){b.preventDefault();jQuery.each(jQuery(".unread"),function(c,a){var d=jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));if(d.hasClass("unread")){d.removeClass("unread");d.addClass("read")}mark_item_as_read(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)})});
$(document).bind("mark_seen",function(b){b.preventDefault();if(is_in_cursor_mode()){jQuery(".cursor").removeClass("seen");jQuery(".cursor").addClass("unseen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status")+" unseen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status").replace(" seen",""));mark_item_as_unseen(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type)}else jQuery.each(jQuery(".selected"),function(c,a){jQuery(a).removeClass("unseen");
jQuery(a).addClass("seen");typeof jQuery(a).attr("status")!=="undefined"&&jQuery(a).attr("status",jQuery(a).attr("status").replace(" unseen",""));jQuery(a).attr("status",jQuery(a).attr("status")+" seen");mark_item_as_seen(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)})});
$(document).bind("mark_unseen",function(b){b.preventDefault();if(is_in_cursor_mode()){jQuery(".cursor").removeClass("seen");jQuery(".cursor").addClass("unseen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status")+" seen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status").replace(" unseen",""));mark_item_as_unseen(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type)}else jQuery.each(jQuery(".selected"),function(c,a){jQuery(a).removeClass("seen");
jQuery(a).addClass("unseen");var d=jQuery(a).attr("status");typeof d!=="undefined"&&jQuery(a).attr("status",d.replace(" seen",""));jQuery(a).attr("status",jQuery(a).attr("status")+" unseen");mark_item_as_unseen(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)})});
$(document).bind("select_all",function(b){b.preventDefault();$.each($("#results > li"),function(c,a){if(!jQuery(a).hasClass("selected")){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")}})});
$(document).bind("select_none",function(b){b.preventDefault();if(is_in_cursor_mode()){jQuery(".cursor").removeClass("selected");jQuery(".cursor").attr("status",jQuery(item_to_mark).attr("status").replace(" selected",""))}else $.each($(".selected"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});
$(document).bind("select_inverse",function(b){b.preventDefault();if(is_in_cursor_mode())if(jQuery(".cursor").hasClass("selected")){jQuery(".cursor").removeClass("selected");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" selected",""))}else{jQuery(".cursor").addClass("selected");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" selected")}else $.each($("#results li"),function(c,a){if(jQuery(a).hasClass("selected")){jQuery(a).removeClass("selected");jQuery(a).attr("status",
jQuery(a).attr("status").replace(" selected",""))}else{jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")}})});
$(document).bind("view_favorites",function(b){b.preventDefault();console.log(location.pathname);console.log("view_favorites clicked");b={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";c=typeof Buleys.view.page!="undefined"&&Buleys.view.page!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/favorites":typeof Buleys.view.slug!="undefined"&&Buleys.view.slug!=""?"http://www.buleys.com/"+Buleys.view.type+"/"+Buleys.view.slug+"/favorites":
"http://www.buleys.com/favorites";history.pushState(b,"view_favorites",c);reload_results()});$(document).bind("deselect_seen",function(b){b.preventDefault();$.each($(".seen"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});
$(document).bind("deselect_unseen",function(b){b.preventDefault();$.each($(".unseen"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});$(document).bind("deselect_read",function(b){b.preventDefault();$.each($(".read"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});
$(document).bind("deselect_unread",function(b){b.preventDefault();$.each($(".unread"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});$(document).bind("deselect_archived",function(b){b.preventDefault();$.each($(".archived"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});
$(document).bind("deselect_unarchived",function(b){b.preventDefault();$.each($(".unarchived"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});$(document).bind("deselect_unseen",function(b){b.preventDefault();$.each($(".unseen"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});
$(document).bind("deselect_unread",function(b){b.preventDefault();$.each($(".unread"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});$(document).bind("deselect_unarchived",function(b){b.preventDefault();$.each($(".unarchived"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});
$(document).bind("select_seen",function(b){b.preventDefault();$.each($(".seen"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")})});$(document).bind("select_unseen",function(b){b.preventDefault();$.each($(".unseen"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")})});
$(document).bind("select_read",function(b){b.preventDefault();$.each($(".read"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")})});$(document).bind("select_unread",function(b){b.preventDefault();$.each($(".unread"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")})});
$(document).bind("select_archived",function(b){b.preventDefault();$.each($(".archived"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")})});$(document).bind("select_unarchived",function(b){b.preventDefault();$.each($(".unarchived"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")})});
$(document).bind("delete",function(b){b.preventDefault();if(is_in_cursor_mode()){delete_item(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);if(jQuery(".cursor").next().length>0)jQuery(".cursor").next().addClass("cursor").prev().remove();else{jQuery(".cursor").remove();jQuery("#results li:first").addClass("cursor")}}else $.each($(".selected"),function(c,a){delete_item(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(a).remove()})});
$(document).bind("undelete",function(b){b.preventDefault();if(is_in_cursor_mode()){undelete_item(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);if(jQuery(".cursor").next().length>0)jQuery(".cursor").next().addClass("cursor").prev().remove();else{jQuery(".cursor").remove();jQuery("#results li:first").addClass("cursor")}}else $.each($(".selected"),function(c,a){console.log("undeleting");console.log(jQuery(a).children("a").attr("href"));undelete_item(jQuery(a).children("a").attr("href"),
Buleys.view.slug,Buleys.view.type);jQuery(a).remove()})});$(document).bind("select",function(b){b.preventDefault();is_in_cursor_mode()?$.each($(".cursor"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")}):$.each($(".selected"),function(c,a){jQuery(a).addClass("selected");jQuery(a).attr("status",jQuery(a).attr("status")+" selected")})});
$(document).bind("deselect",function(b){b.preventDefault();is_in_cursor_mode()?$.each($(".cursor"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))}):$.each($(".selected"),function(c,a){jQuery(a).removeClass("selected");jQuery(a).attr("status",jQuery(a).attr("status").replace(" selected",""))})});
$(document).bind("archive",function(b){b.preventDefault();if(is_in_cursor_mode()){archive_item(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);if(jQuery(".cursor").next().length>0){jQuery(".cursor").next().addClass("cursor").prev().remove();jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" cursor",""))}else{jQuery(".cursor").remove();jQuery("#results li:first").addClass("cursor");jQuery("#results li:first").attr("status",jQuery(item_to_mark).attr("status").replace(" cursor",
""))}}else $.each($(".selected"),function(c,a){archive_item(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);Buleys.view.page!=="favorites"&&Buleys.view.page!=="archive"&&jQuery(a).remove()})});
$(document).bind("read",function(b){b.preventDefault();if(is_in_cursor_mode()){window.open(jQuery(".cursor > a").attr("href"),jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));mark_item_as_read(jQuery(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").addClass("read");jQuery(".cursor").removeClass("unread");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" read");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" unread",
""))}else $.each($(".selected"),function(c,a){window.open(jQuery(a).children("a").attr("href"),jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));mark_item_as_read(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(a).addClass("read");jQuery(a).removeClass("unread");jQuery(a).attr("status",jQuery(a).attr("status")+" read");jQuery(a).attr("status",jQuery(a).attr("status").replace(" unread",""))})});
$(document).bind("unarchive",function(b){b.preventDefault();if(is_in_cursor_mode()){unarchive_item(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").removeClass("archived").addClass(".unarchived");Buleys.view.page=="archive"&&jQuery(".cursor").remove()}else $.each($(".selected"),function(c,a){unarchive_item(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);Buleys.view.page=="archive"&&jQuery(a).remove()})});
$(document).bind("mark_read",function(b){b.preventDefault();if(is_in_cursor_mode()){mark_item_as_read(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").addClass("read");jQuery(".cursor").removeClass("unread");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" read");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" unread",""))}else $.each($(".selected"),function(c,a){mark_item_as_read(jQuery(a).children("a").attr("href"),
Buleys.view.slug,Buleys.view.type);jQuery(a).addClass("read");jQuery(a).removeClass("unread");jQuery(a).attr("status",jQuery(a).attr("status")+" read");jQuery(a).attr("status",jQuery(a).attr("status").replace(" unread",""))})});
$(document).bind("mark_unread",function(b){b.preventDefault();if(is_in_cursor_mode()){remove_item_from_read_database(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").addClass("unread");jQuery(".cursor").removeClass("read");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" unread");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" read",""))}else $.each($(".selected"),function(c,a){remove_item_from_read_database(jQuery(a).children("a").attr("href"),
Buleys.view.slug,Buleys.view.type);jQuery(a).addClass("unread");jQuery(a).removeClass("read");jQuery(a).attr("status",jQuery(a).attr("status")+" read");jQuery(a).attr("status",jQuery(a).attr("status").replace(" unread",""))})});
$(document).bind("mark_all_items_as_unread",function(b){b.preventDefault();jQuery.each(jQuery(".read"),function(c,a){var d=jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));if(d.hasClass("read")){d.removeClass("read");d.addClass("unread");jQuery(d).attr("status",jQuery(a).attr("status")+" unread");jQuery(d).attr("status",jQuery(a).attr("status").replace(" read",""))}remove_item_from_read_database(jQuery(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)})});
jQuery("#console_wrapper").stop(true).animate({opacity:0},0,function(){});jQuery("#overlay").stop(true).animate({opacity:0},0,function(){}).html("");$(".headline a").live("click",function(){var b=$(this).attr("href");c={event:"click",item:$(this).attr("href"),page:slug};var c;c={event:"clickthrough",item:$(this).attr("href"),context:Buleys.view.slug,type:Buleys.view.type};$.post("http://api.buleys.com/feedback/",c,dataType="json",function(){new_window=window.open(b,click_window)})});
$(".sidebar_headline a").live("click",function(){var b=$(this).attr("href"),c;c={event:"click",item:$(this).attr("href"),context:Buleys.view.slug,type:Buleys.view.type};$.post("http://api.buleys.com/feedback/",c,dataType="json",function(){new_window=window.open(b,click_window)})});
jQuery("#results li").live("mouseenter",function(){var b=jQuery(this);if(b.hasClass("unseen")){b.removeClass("unseen");b.addClass("seen")}url_to_preview=b.children("a").attr("href");mark_item_as_seen(url_to_preview,Buleys.view.slug,Buleys.view.type)});
$(document).bind("preview_item",function(b){b.preventDefault();if(0===$(".selected").length){console.log(jQuery(b.target).attr("id"));open_preview(jQuery(b.target).attr("id"))}else if(!is_in_cursor_mode()&&$(".selected").length>0)$.each($(".selected"),function(c,a){var d=jQuery(a);if(d.hasClass("unseen")){d.removeClass("unseen");d.addClass("seen")}url_to_preview=d.children("a").attr("href");mark_item_as_seen(url_to_preview,Buleys.view.slug,Buleys.view.type);load_item_to_overlay(url_to_preview);jQuery("#overlay").stop(true).animate({opacity:1},
100,function(){})});else if($(".selected").length>0){b=jQuery(".cursor");if(b.hasClass("unseen")){b.removeClass("unseen");b.addClass("seen")}url_to_preview=b.children("a").attr("href");mark_item_as_seen(url_to_preview,Buleys.view.slug,Buleys.view.type);load_item_to_overlay(url_to_preview);jQuery("#overlay").stop(true).animate({opacity:1},100,function(){})}});
$(document).bind("close_item_preview",function(b){b.preventDefault();if(is_in_cursor_mode()){b=jQuery(".cursor");if(b.hasClass("unseen")){b.removeClass("unseen");b.addClass("seen")}url_to_preview=b.children("a").attr("href");b="#overlay_"+url_to_preview.replace(/[^a-zA-Z0-9-_]+/g,"");jQuery(b).length>0&&jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})}else $(".selected").length>0?$.each($(".selected"),function(c,a){var d=jQuery(a),e=d.children("a").attr("href");
if(d.hasClass("unread")){d.removeClass("unread");d.addClass("read")}d="#overlay_"+e.replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery(d).length>0){d=jQuery(a);if(d.hasClass("unseen")){d.removeClass("unseen");d.addClass("seen")}e=d.children("a").attr("href");jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})}}):jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});
$(document).bind("results li:not(.favorite_status)",function(){var b=jQuery(this),c=b.children("a").attr("href");if(b.hasClass("unread")){b.removeClass("unread");b.addClass("read")}if(jQuery(this).hasClass("star_icon")===false&&jQuery(this).hasClass("empty_star_icon")===false){var a="#overlay_"+c.replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery(a).length>0&&jQuery(b).hasClass("selected"))jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")});else if(!jQuery(b).hasClass("selected")){jQuery("#overlay").stop(true).animate({opacity:1},
100,function(){});load_item_to_overlay(c)}b.addClass("selected")}});$(".selected").live("click",function(){$(this).removeClass("selected")});$("#results li").live("mouseleave",function(){});
