$("#dologin").live("click",function(a){a.preventDefault();$("#dologin").remove();$("#login_status_pane").append('<div id="minimize_login_controls"><a href="#" id="dologinboxminimize" class="loginboxminimizelink enter_door_icon"></a></div><div id="login_form"><a href="#" id="doregistration" class="registrationlink">Register</a> or Login:<br/><input id="email" type="text" value="your@email.here" name="email" class="defaulttext" /><br/><input id="password"  class="defaulttext" type="password" value="p4s5w0rd" name="password" /></div><div id="login_buttons"><a href="#" id="doresetpassword" class="resetpasswordlink">Reset Password</a><br/><a href="#" id="dologinsubmit" class="submitloginform">Login</a></div></div>')});
$("a#get_inbox").live("click",function(a){a.preventDefault();$("#mini_inbox_box").html('<div id="mini_inbox_wrapper"><div id="minimize_mini_inbox_controls"><a href="#" id="minimize_inbox cross_link"></a></div><ul id="mini_inbox_list"><li>Loading...</li></ul></div>');add_topics_to_mini_inbox()});$("#minimize_inbox").live("click",function(a){a.preventDefault();$("#mini_inbox_box").hasClass("waiting_inbox")?$("#mini_inbox_box").html('<a href="#" id="get_inbox inbox"></a>'):$("#mini_inbox_box").html('<a href="#" id="get_inbox empty_inbox"></a>')});
$("#dologinboxminimize").live("click",function(a){a.preventDefault();$("#login_status_pane").html('<a href="#" id="dologin" class="getloginform exit_door_link"></a>')});$("#show_commands").live("click",function(a){a.preventDefault();$("#result_controls").show()});$("#hide_commands").live("click",function(a){a.preventDefault();$("#result_controls").hide()});
$("html").live("keyup",function(a){if(a.keyCode==68)Buleys.shortcuts.d_depressed=false;else if(a.keyCode==83)Buleys.shortcuts.s_depressed=false;else if(a.keyCode==16)Buleys.shortcuts.shift_depressed=false;else if(a.keyCode==72)Buleys.shortcuts.s_depressed||Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$("#view_index").click():$("#close_item_preview").click());else if(a.keyCode==76){if(!Buleys.shortcuts.s_depressed)if(!Buleys.shortcuts.d_depressed)if(Buleys.shortcuts.shift_depressed)$("#view_home").click();
else{$("#preview_item").click();jQuery(".cursor")}}else if(a.keyCode==78){$("#preview_item").click();jQuery(".selected").length>0?jQuery("#results li.selected:first").addClass("cursor"):jQuery("#results li:first").addClass("cursor")}else if(a.keyCode==74)if(jQuery(".cursor").next().length>0)jQuery(".cursor").removeClass("cursor").next().addClass("cursor");else{jQuery(".cursor").removeClass("cursor");jQuery("#results li:first").addClass("cursor")}else if(a.keyCode==75)if(jQuery(".cursor").prev().length>
0)jQuery(".cursor").removeClass("cursor").prev().addClass("cursor");else{jQuery(".cursor").removeClass("cursor");jQuery("#results li:last").addClass("cursor")}else if(a.keyCode==27){jQuery(".cursor").removeClass("cursor");$("#close_all").click()}else if(a.keyCode==77)jQuery(".cursor").removeClass("cursor");else if(a.keyCode==219)$("#preview_item").click();else if(a.keyCode==221)$("#close_item_preview").click();else if(a.keyCode==89)$("#show_commands").click();else if(a.keyCode==85)$("#hide_commands").click();
else if(a.keyCode==65)if(Buleys.shortcuts.s_depressed)$("#select_all").click();else Buleys.shortcuts.d_depressed&&$("#select_none").click();else if(a.keyCode==82)if(Buleys.shortcuts.s_depressed)$("#select_unread").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_unread").click();else Buleys.shortcuts.shift_depressed?$("#view_unread").click():$("#mark_unread").click();else if(a.keyCode!=13)if(a.keyCode==73)$("#select").click();else if(a.keyCode==79)$("#deselect").click();else if(a.keyCode==
69)if(Buleys.shortcuts.s_depressed)$("#select_read").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_read").click();else Buleys.shortcuts.shift_depressed?$("#view_read").click():$("#mark_read").click();else if(a.keyCode==88)if(Buleys.shortcuts.s_depressed)$("#select_none").click();else Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$("#view_trash").click():$("#delete").click());else if(a.keyCode==67)if(Buleys.shortcuts.s_depressed)$("#select_archived").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_archived").click();
else Buleys.shortcuts.shift_depressed?$("#view_archive").click():$("#archive").click();else if(a.keyCode==86)if(Buleys.shortcuts.s_depressed)$("#select_unarchived").click();else Buleys.shortcuts.d_depressed?$("#deselect_unarchived").click():$("#unarchive").click();else if(a.keyCode==70)if(Buleys.shortcuts.s_depressed)$("#select_favorites").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_favorites").click();else Buleys.shortcuts.shift_depressed?$("#view_favorites").click():$("#favorite").click();
else if(a.keyCode==71)if(Buleys.shortcuts.s_depressed)$("#select_unfavorite").click();else Buleys.shortcuts.d_depressed?$("#deselect_unfavorite").click():$("#unfavorite").click();else if(a.keyCode==81)if(Buleys.shortcuts.s_depressed)$("#select_seen").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_seen").click();else Buleys.shortcuts.shift_depressed?$("#view_seen").click():$("#mark_seen").click();else if(a.keyCode==87)if(Buleys.shortcuts.s_depressed)$("#select_unseen").click();else if(Buleys.shortcuts.d_depressed)$("#deselect_unseen").click();
else Buleys.shortcuts.shift_depressed?$("#view_unseen").click():$("#mark_unseen").click();else if(a.keyCode==90)if(Buleys.shortcuts.s_depressed)$("#select_inverse").click();else Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$("#view_index").click():$("#refresh").click());else if(a.keyCode==73)$("#deselect").click();else a.keyCode==79&&$("#select").click()});
$("html").live("keydown",function(a){if(a.keyCode==68)Buleys.shortcuts.d_depressed=true;else if(a.keyCode==83)Buleys.shortcuts.s_depressed=true;else if(a.keyCode==16)Buleys.shortcuts.shift_depressed=true});$(window).bind("popstate",function(){console.log(location.pathname);if(Buleys.session.database_is_open){reload_results();Buleys.session.database_is_open=true}});
$(".get_settings").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_settings clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};console.log(history);history.pushState(a,"settings","http://buleys.com/settings");reload_results()});
$("#get_login").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("get_login clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};history.pushState(a,"login","http://buleys.com/start");reload_results()});
$("#view_seen").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_seen clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";history.pushState(a,"view_seen",typeof page!="undefined"&&page!=""?"http://buleys.com/"+type+"/"+slug+"/seen":typeof slug!="undefined"&&slug!=""?"http://buleys.com/"+type+"/"+slug+"/seen":"http://buleys.com/seen");reload_results()});
$("#view_unseen").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_unseen clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";history.pushState(a,"view_unseen",typeof page!="undefined"&&page!=""?"http://buleys.com/"+type+"/"+slug+"/unseen":typeof slug!="undefined"&&slug!=""?"http://buleys.com/"+type+"/"+slug+"/unseen":"http://buleys.com/unseen");reload_results()});
$("#view_read").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_read clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";history.pushState(a,"view_read",typeof page!="undefined"&&page!=""?"http://buleys.com/"+type+"/"+slug+"/read":typeof slug!="undefined"&&slug!=""?"http://buleys.com/"+type+"/"+slug+"/read":"http://buleys.com/read");reload_results()});
$("#view_unread").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_unread clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";history.pushState(a,"view_unread",typeof page!="undefined"&&page!=""?"http://buleys.com/"+type+"/"+slug+"/unread":typeof slug!="undefined"&&slug!=""?"http://buleys.com/"+type+"/"+slug+"/unread":"http://buleys.com/unread");reload_results()});
$("#view_trash").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_trash clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";history.pushState(a,"view_trash",typeof page!="undefined"&&page!=""?"http://buleys.com/"+type+"/"+slug+"/trash":typeof slug!="undefined"&&slug!=""?"http://buleys.com/"+type+"/"+slug+"/trash":"http://buleys.com/trash");reload_results()});
$("#view_archive").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_archive clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";history.pushState(a,"view_archive",typeof page!="undefined"&&page!=""?"http://buleys.com/"+type+"/"+slug+"/archive":typeof slug!="undefined"&&slug!=""?"http://buleys.com/"+type+"/"+slug+"/archive":"http://buleys.com/archive");reload_results()});
$("#view_favorites").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_favorites clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";history.pushState(a,"view_favorites",typeof page!="undefined"&&page!=""?"http://buleys.com/"+type+"/"+slug+"/favorites":typeof slug!="undefined"&&slug!=""?"http://buleys.com/"+type+"/"+slug+"/favorites":"http://buleys.com/favorites");reload_results()});
$("#view_index").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_index clicked");jQuery("#page_meta").html("");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};history.pushState(a,"view_index","http://buleys.com/");reload_results()});
$("#view_home").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_home clicked");jQuery("#page_meta").html("");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};var c="";if(typeof slug!="undefined"&&slug!="")c="http://buleys.com/"+type+"/"+slug+"/";else if(typeof type!="undefined"&&type!="")c="http://buleys.com/"+type+"/";history.pushState(a,"view_home",c);reload_results()});
$("#dologinsubmit").live("click",function(a){a.preventDefault();$('[name="password"]').val()&&request_login($('[name="email"]').val(),$('[name="password"]').val())});
$(".unfav_link").live("click",function(a){a.preventDefault();jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("unfav_link").addClass("fav_link");
jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");remove_item_from_favorites_database($(this).attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("unstar",$(this).attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item removed from favorites</p>");
setTimeout("fade_console_message()",1E3)});
$("#favorite").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("unfav_link");
jQuery("#favorite_"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(".cursor a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",$(".cursor a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item favorited</p>");
setTimeout("fade_console_message()",1E3)}else $.each($(".selected"),function(c,b){jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("unfav_link");
jQuery("#favorite_"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",$(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);
send_to_console("<p>item favorited</p>");setTimeout("fade_console_message()",1E3)})});
$("#unfavorite").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("star_icon").addClass("empty_star_icon");jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("unfav_link");
jQuery("#favorite_"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");remove_item_from_favorites_database($(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("unstar",$(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);
send_to_console("<p>item removed from favorites</p>");setTimeout("fade_console_message()",1E3)}else $.each($(".selected"),function(c,b){jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("star_icon").addClass("empty_star_icon");jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,
"")).children(".favorite_status").children("a").removeClass("unfav_link");jQuery("#favorite_"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");remove_item_from_favorites_database($(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);
post_feedback("unstar",$(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item removed from favorites</p>");setTimeout("fade_console_message()",1E3)})});
$(".fav_link").live("click",function(a){a.preventDefault();jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("a").removeClass("fav_link").addClass("unfav_link");
jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(this).attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",$(this).attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item favorited</p>");
setTimeout("fade_console_message()",1E3)});$(".close_item_preview").live("click",function(a){a.preventDefault();jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});$(".sidebar_close_link").live("click",function(a){a.preventDefault();jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});$("#close_all").live("click",function(a){a.preventDefault();jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});
$(".mark_item_as_unread").live("click",function(a){a.preventDefault();$(this).removeClass("empty_star_icon").addClass("star_icon");$(this).removeClass("unfav_link");$(this).addClass("fav_link");a=jQuery("#"+jQuery(this).attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));if(a.hasClass("read")){a.removeClass("read");a.addClass("unread")}remove_item_from_read_database($(this).attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>marked as unread</p>");setTimeout("fade_console_message()",1E3)});
$("#mark_all_items_as_read").live("click",function(a){a.preventDefault();jQuery.each(jQuery(".unread"),function(c,b){var d=jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));if(d.hasClass("unread")){d.removeClass("unread");d.addClass("read")}mark_item_as_read(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)})});
$("#mark_seen").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){jQuery(".cursor").removeClass("seen");jQuery(".cursor").addClass("unseen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status")+" unseen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status").replace(" seen",""));mark_item_as_unseen(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type)}else jQuery.each(jQuery(".selected"),function(c,b){jQuery(b).removeClass("unseen");
jQuery(b).addClass("seen");typeof jQuery(b).attr("status")!=="undefined"&&jQuery(b).attr("status",jQuery(b).attr("status").replace(" unseen",""));jQuery(b).attr("status",jQuery(b).attr("status")+" seen");mark_item_as_seen(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)})});
$("#mark_unseen").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){jQuery(".cursor").removeClass("seen");jQuery(".cursor").addClass("unseen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status")+" seen");jQuery(item_to_mark).attr("status",jQuery(item_to_mark).attr("status").replace(" unseen",""));mark_item_as_unseen(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type)}else jQuery.each(jQuery(".selected"),function(c,b){jQuery(b).removeClass("seen");
jQuery(b).addClass("unseen");var d=jQuery(b).attr("status");typeof d!=="undefined"&&jQuery(b).attr("status",d.replace(" seen",""));jQuery(b).attr("status",jQuery(b).attr("status")+" unseen");mark_item_as_unseen(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)})});
$("#select_all").live("click",function(a){a.preventDefault();$.each($("#results > li"),function(c,b){if(!jQuery(b).hasClass("selected")){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")}})});
$("#select_none").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){jQuery(".cursor").removeClass("selected");jQuery(".cursor").attr("status",jQuery(item_to_mark).attr("status").replace(" selected",""))}else $.each($(".selected"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});
$("#select_inverse").live("click",function(a){a.preventDefault();if(is_in_cursor_mode())if(jQuery(".cursor").hasClass("selected")){jQuery(".cursor").removeClass("selected");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" selected",""))}else{jQuery(".cursor").addClass("selected");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" selected")}else $.each($("#results li"),function(c,b){if(jQuery(b).hasClass("selected")){jQuery(b).removeClass("selected");jQuery(b).attr("status",
jQuery(b).attr("status").replace(" selected",""))}else{jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")}})});$("#select_favorites").live("click",function(a){a.preventDefault();$.each($(".favorited"),function(c,b){if(!jQuery(b).hasClass("selected")){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")}})});
$("#deselect_seen").live("click",function(a){a.preventDefault();$.each($(".seen"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});$("#deselect_unseen").live("click",function(a){a.preventDefault();$.each($(".unseen"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});
$("#deselect_favorites").live("click",function(a){a.preventDefault();$.each($(".favorited"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});$("#deselect_read").live("click",function(a){a.preventDefault();$.each($(".read"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});
$("#deselect_unread").live("click",function(a){a.preventDefault();$.each($(".unread"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});$("#deselect_archived").live("click",function(a){a.preventDefault();$.each($(".archived"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});
$("#deselect_unarchived").live("click",function(a){a.preventDefault();$.each($(".unarchived"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});$("#deselect_unseen").live("click",function(a){a.preventDefault();$.each($(".unseen"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});
$("#deselect_unread").live("click",function(a){a.preventDefault();$.each($(".unread"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});$("#deselect_unarchived").live("click",function(a){a.preventDefault();$.each($(".unarchived"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});
$("#select_seen").live("click",function(a){a.preventDefault();$.each($(".seen"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")})});$("#select_unseen").live("click",function(a){a.preventDefault();$.each($(".unseen"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")})});
$("#select_read").live("click",function(a){a.preventDefault();$.each($(".read"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")})});$("#select_unread").live("click",function(a){a.preventDefault();$.each($(".unread"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")})});
$("#select_archived").live("click",function(a){a.preventDefault();$.each($(".archived"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")})});$("#select_unarchived").live("click",function(a){a.preventDefault();$.each($(".unarchived"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")})});
$("#delete").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){delete_item(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);if(jQuery(".cursor").next().length>0)jQuery(".cursor").next().addClass("cursor").prev().remove();else{jQuery(".cursor").remove();jQuery("#results li:first").addClass("cursor")}}else $.each($(".selected"),function(c,b){delete_item(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(b).remove()})});
$("#select").live("click",function(a){a.preventDefault();is_in_cursor_mode()?$.each($(".cursor"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")}):$.each($(".selected"),function(c,b){jQuery(b).addClass("selected");jQuery(b).attr("status",jQuery(b).attr("status")+" selected")})});
$("#deselect").live("click",function(a){a.preventDefault();is_in_cursor_mode()?$.each($(".cursor"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))}):$.each($(".selected"),function(c,b){jQuery(b).removeClass("selected");jQuery(b).attr("status",jQuery(b).attr("status").replace(" selected",""))})});
$("#archive").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){archive_item(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);if(jQuery(".cursor").next().length>0){jQuery(".cursor").next().addClass("cursor").prev().remove();jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" cursor",""))}else{jQuery(".cursor").remove();jQuery("#results li:first").addClass("cursor");jQuery("#results li:first").attr("status",jQuery(item_to_mark).attr("status").replace(" cursor",
""))}}else $.each($(".selected"),function(c,b){archive_item(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);Buleys.view.page!=="favorites"&&Buleys.view.page!=="archive"&&jQuery(b).remove()})});
$("#read").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){window.open(jQuery(".cursor > a").attr("href"),jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));mark_item_as_read(jQuery(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").addClass("read");jQuery(".cursor").removeClass("unread");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" read");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" unread",
""))}else $.each($(".selected"),function(c,b){window.open(jQuery(b).children("a").attr("href"),jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));mark_item_as_read(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(b).addClass("read");jQuery(b).removeClass("unread");jQuery(b).attr("status",jQuery(b).attr("status")+" read");jQuery(b).attr("status",jQuery(b).attr("status").replace(" unread",""))})});
$("#unarchive").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){unarchive_item(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").removeClass("archived").addClass(".unarchived");Buleys.view.page=="archive"&&jQuery(".cursor").remove()}else $.each($(".selected"),function(c,b){unarchive_item(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);Buleys.view.page=="archive"&&jQuery(b).remove()})});
$("#mark_read").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){mark_item_as_read(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").addClass("read");jQuery(".cursor").removeClass("unread");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" read");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" unread",""))}else $.each($(".selected"),function(c,b){mark_item_as_read(jQuery(b).children("a").attr("href"),
Buleys.view.slug,Buleys.view.type);jQuery(b).addClass("read");jQuery(b).removeClass("unread");jQuery(b).attr("status",jQuery(b).attr("status")+" read");jQuery(b).attr("status",jQuery(b).attr("status").replace(" unread",""))})});
$("#mark_unread").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){remove_item_from_read_database(jQuery(".cursor").children("a").attr("href"),Buleys.view.slug,Buleys.view.type);jQuery(".cursor").addClass("unread");jQuery(".cursor").removeClass("read");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status")+" unread");jQuery(".cursor").attr("status",jQuery(".cursor").attr("status").replace(" read",""))}else $.each($(".selected"),function(c,b){remove_item_from_read_database(jQuery(b).children("a").attr("href"),
Buleys.view.slug,Buleys.view.type);jQuery(b).addClass("unread");jQuery(b).removeClass("read");jQuery(b).attr("status",jQuery(b).attr("status")+" read");jQuery(b).attr("status",jQuery(b).attr("status").replace(" unread",""))})});
$("#mark_all_items_as_unread").live("click",function(a){a.preventDefault();jQuery.each(jQuery(".read"),function(c,b){var d=jQuery("#"+jQuery(b).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,""));if(d.hasClass("read")){d.removeClass("read");d.addClass("unread");jQuery(d).attr("status",jQuery(b).attr("status")+" unread");jQuery(d).attr("status",jQuery(b).attr("status").replace(" read",""))}remove_item_from_read_database(jQuery(b).children("a").attr("href"),Buleys.view.slug,Buleys.view.type)});
jQuery("#logout").live("click",function(){account_logout()});jQuery(".do_logout").live("click",function(){account_logout()});jQuery(".do_logout").live("click",function(){account_logout()});jQuery(".submitthelogin").live("click",function(){});jQuery(".defaulttext").live("click",function(){jQuery(this).val("");jQuery(this).removeClass("defaulttext")})});
$(".delete_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var c=$(this).attr("type"),b=$(this).attr("slug");$(this).parent().parent().remove();remove_category_for_item(a.replace(/[^a-zA-Z0-9-_]+/g,""),c,b);$(this).hasClass("voted")||post_feedback("delete_category",a,c,b)});
$(".follow_topic").live("click",function(a){a.preventDefault();a=$(this).attr("key");var c=$(this).attr("type");if(typeof a=="undefined")a=slug;if(typeof c=="undefined"||c=="")c=type;add_follow_if_doesnt_exist(c,a);post_feedback("follow","",a,c);$(this).removeClass("empty_heart_icon").addClass("heart_icon");$(this).removeClass("follow_topic");$(this).addClass("unfollow_topic")});
$(".unfollow_topic").live("click",function(a){a.preventDefault();a=$(this).attr("key");var c=$(this).attr("type");if(typeof a=="undefined")a=slug;if(typeof c=="undefined"||c=="")c=type;remove_follow(c,a);post_feedback("unfollow","",a,c);$(this).removeClass("heart_icon").addClass("empty_heart_icon");$(this).removeClass("unfollow_topic");$(this).addClass("follow_topic")});
$(".subscribe_topic").live("click",function(a){a.preventDefault();a=$(this).attr("key");var c=$(this).attr("type");if(typeof a=="undefined")a=slug;if(typeof c=="undefined"||c=="")c=type;add_subscription_if_doesnt_exist(c,a);post_feedback("subscribe","",a,c);$(this).removeClass("empty_inbox_icon").addClass("inbox_icon");$(this).removeClass("subscribe_topic");$(this).addClass("unsubscribe_topic")});
$(".unsubscribe_topic").live("click",function(a){a.preventDefault();a=$(this).attr("key");var c=$(this).attr("type");if(typeof a=="undefined")a=slug;if(typeof c=="undefined"||c=="")c=type;remove_subscription(c,a);post_feedback("subscribe","",a,c);$(this).removeClass("inbox_icon").addClass("empty_inbox_icon");$(this).removeClass("unsubscribe_topic");$(this).addClass("subscribe_topic")});
$(".vote_up_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var c=$(this).attr("type"),b=$(this).attr("slug"),d="";d=a.replace(/[^a-zA-Z0-9-_]+/g,"")+c.toLowerCase()+b.toLowerCase();add_or_update_vote(d,1);$(this).hasClass("voted")||post_feedback("category_upvote",a,c,b);$(this).addClass("voted")});
$(".vote_down_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var c=$(this).attr("type"),b=$(this).attr("slug"),d="";d=a.replace(/[^a-zA-Z0-9-_]+/g,"")+c.toLowerCase()+b.toLowerCase();add_or_update_vote(d,-1);$(this).hasClass("voted")||post_feedback("category_downvote",a,c,b);$(this).addClass("voted")});
$(".vote_up").live("click",function(a){a.preventDefault();a=$(this).attr("link").replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery("#overlay_upvote_"+a).hasClass("vote")){jQuery("#overlay_upvote_"+a).removeClass("thumb_up_icon").addClass("empty_thumb_up_icon");$(".vote").removeClass("vote");$(this).parent().removeClass("voted");post_feedback("item_remove_upvote",a,Buleys.view.type,Buleys.view.slug);remove_vote(a)}else{jQuery("#overlay_downvote_"+a).removeClass("thumb_icon").addClass("empty_thumb_icon");jQuery("#overlay_upvote_"+
a).removeClass("empty_thumb_up_icon").addClass("thumb_up_icon");$(".vote").removeClass("vote");$(this).parent().addClass("voted");$(this).addClass("vote");post_feedback("item_upvote",a,Buleys.view.type,Buleys.view.slug);add_or_update_vote(a,1)}});
$(".vote_down").live("click",function(a){a.preventDefault();a=$(this).attr("link").replace(/[^a-zA-Z0-9-_]+/g,"");var c=a.replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery("#overlay_downvote_"+c).hasClass("vote")){jQuery("#overlay_downvote_"+c).removeClass("empty_thumb_icon").addClass("thumb_icon");$(".vote").removeClass("vote");$(this).parent().removeClass("voted");post_feedback("item_remove_downvote",a,Buleys.view.type,Buleys.view.slug);remove_vote(a)}else{jQuery("#overlay_downvote_"+c).removeClass("empty_thumb_icon").addClass("thumb_icon");
jQuery("#overlay_upvote_"+c).removeClass("thumb_up_icon").addClass("empty_thumb_up_icon");$(".vote").removeClass("vote");$(this).parent().addClass("voted");$(this).addClass("vote");post_feedback("item_downvote",a,Buleys.view.type,Buleys.view.slug);add_or_update_vote(a,-1)}});jQuery("#console_wrapper").stop(true).animate({opacity:0},0,function(){});jQuery("#overlay").stop(true).animate({opacity:0},0,function(){}).html("");$("#overlay .category").live("mouseenter",function(a){a.preventDefault();add_category_controls(jQuery(this))});
$("#overlay .category").live("mouseleave",function(a){a.preventDefault();jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .delete_category").remove()});
$(".headline a").live("click",function(){var a=$(this).attr("href");c={event:"click",item:$(this).attr("href"),page:slug};var c;c={event:"clickthrough",item:$(this).attr("href"),context:Buleys.view.slug,type:Buleys.view.type};$.post("/feedback/index.php",c,dataType="json",function(){new_window=window.open(a,click_window)})});
$(".sidebar_headline a").live("click",function(){var a=$(this).attr("href"),c;c={event:"click",item:$(this).attr("href"),context:Buleys.view.slug,type:Buleys.view.type};$.post("/feedback/index.php",c,dataType="json",function(){new_window=window.open(a,click_window)})});
jQuery("#results li").live("mouseenter",function(){var a=jQuery(this);if(a.hasClass("unseen")){a.removeClass("unseen");a.addClass("seen")}url_to_preview=a.children("a").attr("href");mark_item_as_seen(url_to_preview,Buleys.view.slug,Buleys.view.type)});
jQuery("#preview_item").live("click",function(a){a.preventDefault();if(!is_in_cursor_mode()&&$(".selected").length>0)$.each($(".selected"),function(c,b){var d=jQuery(b);if(d.hasClass("unseen")){d.removeClass("unseen");d.addClass("seen")}url_to_preview=d.children("a").attr("href");mark_item_as_seen(url_to_preview,Buleys.view.slug,Buleys.view.type);load_item_to_overlay(url_to_preview);jQuery("#overlay").stop(true).animate({opacity:1},100,function(){})});else if($(".selected").length>0){a=jQuery(".cursor");
if(a.hasClass("unseen")){a.removeClass("unseen");a.addClass("seen")}url_to_preview=a.children("a").attr("href");mark_item_as_seen(url_to_preview,Buleys.view.slug,Buleys.view.type);load_item_to_overlay(url_to_preview);jQuery("#overlay").stop(true).animate({opacity:1},100,function(){})}});
$("#close_item_preview").live("click",function(a){a.preventDefault();if(is_in_cursor_mode()){a=jQuery(".cursor");if(a.hasClass("unseen")){a.removeClass("unseen");a.addClass("seen")}url_to_preview=a.children("a").attr("href");a="#overlay_"+url_to_preview.replace(/[^a-zA-Z0-9-_]+/g,"");jQuery(a).length>0&&jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})}else $(".selected").length>0?$.each($(".selected"),function(c,b){var d=jQuery(b),e=d.children("a").attr("href");
if(d.hasClass("unread")){d.removeClass("unread");d.addClass("read")}d="#overlay_"+e.replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery(d).length>0){d=jQuery(b);if(d.hasClass("unseen")){d.removeClass("unseen");d.addClass("seen")}e=d.children("a").attr("href");jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})}}):jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")})});
jQuery("#results li").live("click",function(){var a=jQuery(this),c=a.children("a").attr("href");if(a.hasClass("unread")){a.removeClass("unread");a.addClass("read")}var b="#overlay_"+c.replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery(b).length>0&&jQuery(a).hasClass("selected"))jQuery("#overlay").stop(true).animate({opacity:0},500,function(){jQuery("#overlay").html("")});else if(!jQuery(a).hasClass("selected")){jQuery("#overlay").stop(true).animate({opacity:1},100,function(){});load_item_to_overlay(c)}a.addClass("selected")});
$(".selected").live("click",function(){$(this).removeClass("selected")});$("#results li").live("mouseleave",function(){});$("#show_button").live("click",function(){send_notification_to_desktop()});
