function new_seen_transaction(){jQuery(document).trigger("new_seen_transaction");try{var a=Buleys.db.transaction(["seen"],IDBTransaction.READ_WRITE,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("seen")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.version,10));a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("seen",{keyPath:"link"},true);Buleys.objectStore.createIndex("topic_slug","topic_slug",{unique:false});
Buleys.objectStore.createIndex("topic_type","topic_type",{unique:false});Buleys.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function get_seen(a,b,d,c,g){jQuery(document).trigger("get_seen");if(typeof g=="undefined")g=false;typeof d=="undefined"||d==null||parseInt(d);typeof c=="undefined"||c==null?(new Date).getTime():parseInt(c);new_categories_transaction();Buleys.index=Buleys.objectStoreCategories.index("slug");a=IDBKeyRange.only(b);a=Buleys.index.openCursor(a);a.onsuccess=function(e){if(e.target.result){e=e.target.result;var f=e.value;new_seen_transaction();Buleys.objectStore.get(f.link).onsuccess=function(h){if(typeof h.target.result!==
"undefined"&&g!==true)jQuery("#"+f.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item(f.link);else typeof h.target.result=="undefined"&&g==true&&jQuery("#"+f.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item(f.link)};e["continue"]()}};a.onerror=function(){}}
function mark_item_as_seen(a,b,d){jQuery(document).trigger("mark_item_as_seen");new_seen_transaction();a={link:a,topic_slug:b,topic_type:d,modified:(new Date).getTime()};var c=Buleys.objectStore.add(a);c.onsuccess=function(){Buleys.objectId=c.result};c.onerror=function(){}}function mark_item_as_unseen(a){jQuery(document).trigger("mark_item_as_unseen");new_seen_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function add_item_as_seen(a){jQuery(document).trigger("add_item_as_seen");new_seen_transaction();a={link:a,modified:(new Date).getTime()};var b=Buleys.objectStore.add(a);b.onsuccess=function(){Buleys.objectId=b.result};b.onerror=function(){}}
function check_if_item_is_seen(a){jQuery(document).trigger("check_if_item_is_seen");new_seen_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){checker=b;typeof b.result!="undefined"?jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("seen"):jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("unseen")};b.onerror=function(){}}
function add_item_to_seens_database(a,b,d){jQuery(document).trigger("add_item_to_seens_database");new_seen_transaction();a={item_link:a,topic_slug:b,topic_type:d,modified:(new Date).getTime()};var c=Buleys.objectStore.add(a);c.onsuccess=function(){Buleys.objectId=c.result};c.onerror=function(){}}
function remove_item_from_seens_database(a){jQuery(document).trigger("remove_item_from_seens_database");new_seen_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}};
