function new_settings_transaction(){try{var a=Buleys.db.transaction(["settings"],IDBTransaction.READ_WRITE,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("settings")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.db.version)+1);a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("settings",{keyPath:"option_name"},true);Buleys.objectStore.createIndex("option_value","option_value",{unique:false})};a.onerror=function(){}}}
function get_settings(){console.log("get_settings(): ");Buleys.view.loaded="settings";get_settings();var a=get_local_storage("session_id");typeof a=="undefined"||a==null||a==""?jQuery("#main").append('<div id="account"><input id="password" type="password" value="p4s5w0rd" name="password" /><br/><br/><a href="#" id="update_settings_button" class="update_settings">Update</a> or <a href="#" id="clear_form_button" class="clear_form">Clear</a></div></div></div>'):jQuery("#main").append("<div id='account'>Already logged in with session id <code>"+
a+"</code>.<br/><br/><a href='#' class='do_logout'>Click here</a> to log out.</div>");jQuery("#main").append('<input type="number" min="0" max="10" step="2" value="6"> <input type="number" min="0" max="10" step="2" value="6">')}
function get_settings_old(){try{new_settings_transaction();Buleys.index=Buleys.objectStore.index("option_name");var a=Buleys.index.openCursor();a.onsuccess=function(){var c=a.result;if(c)if(c.length>=0){Buleys.view.type="settings";jQuery.each(c,function(d,e){console.log("get_settings(): "+e)})}};request.onerror=function(){}}catch(b){}}function save_settings(){add_or_update_setting("hotkeys",Buleys.settings)}
function load_settings_into_dom(){new_settings_transaction();Buleys.index=Buleys.objectStore.index();var a=Buleys.objectStore.openCursor();a.onsuccess=function(){new_settings_transaction();var b=a.result;b&&b.length>=0&&jQuery.each(b,function(c,d){Buleys.settings[c]=d})};request.onerror=function(){}}function remove_setting(a){new_settings_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function load_all_settings_into_dom(){new_settings_transaction();var a=Buleys.objectStore.openCursor();a.onsuccess=function(){typeof a.result!=="undefined"&&a.result.length>=0&&jQuery.each(a.result,function(b,c){Buleys.settings[c.option_name]=c.option_value})};a.onerror=function(){}}
function add_or_update_setting(a,b){new_settings_transaction();if(typeof b=="undefined")b="";var c=Buleys.objectStore.get(a);c.onsuccess=function(){typeof c.result=="undefined"?add_setting_to_settings_database(a,b):update_setting_in_settings_database(a,b)};c.onerror=function(){}}
function add_setting_to_settings_database(a,b){new_settings_transaction();var c={option_name:a,option_value:b,modified:(new Date).getTime()},d=Buleys.objectStore.add(c);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}function update_setting_in_settings_database(a,b){new_settings_transaction();var c={option_name:a,option_value:b,modified:(new Date).getTime()},d=Buleys.objectStore.put(c);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}
function get_settings_page(){var a=get_local_storage("session_id");typeof a==="undefined"||a===null?jQuery("#main").append("<div od='login_prompt'>Logged in with session id <code>"+ +"</code>.<br/><br/><a href='#' class='do_logout'>Click here</a> to log out.</div>"):jQuery("#main").append("<div id='configuration_panel'><h3>Configuration</h3><p><input type='range' min='0' max='10' step='2' value='6'></p><p><input type='number' min='0' max='10' step='2' value='6'></p></div>")}
function get_setting_type(a){return get_local_storage("setting_type_"+a)}function set_setting_type(a,b){return set_local_storage("setting_type_"+a,b)}function get_setting(a){return get_local_storage("setting_type_"+a)}function set_setting(a,b){return set_local_storage("setting_type_"+a,b)}
$(".get_settings").live("click",function(a){a.preventDefault();console.log(location.pathname);console.log("view_settings clicked");a={page:Buleys.view.page,slug:Buleys.view.slug,type:Buleys.view.type,time:(new Date).getTime()};console.log(history);history.pushState(a,"settings","http://www.buleys.com/settings");reload_results()});
