function load_page_title_info(a){typeof a.name!="undefined"&&jQuery("a .topic_name").length>0&&!jQuery("#page_meta").indexOf("<a href='/"+a.type+"/"+a.key+"' class='topic_name'>"+a.name+"</a>")&&jQuery("#page_meta").append("<a href='/"+a.type+"/"+a.key+"' class='topic_name'>"+a.name+"</a>");typeof a.subsector!="undefined"&&jQuery("a .sector_name").length>0&&!jQuery("#page_meta").indexOf("<a href='/sector/"+getURLSlug(a.subsector).toLowerCase()+"' class='sector_name'>"+a.subsector+"</a>")&&jQuery("#page_meta").append("<a href='/sector/"+
getURLSlug(a.subsector).toLowerCase()+"' class='sector_name'>"+a.subsector+"</a>");typeof a.sector!="undefined"&&jQuery("a .subsector_name").length>0&&!jQuery("#page_meta").indexOf("<a href='/sector/"+getURLSlug(a.sector).toLowerCase()+"' class='subsector_name'>"+a.sector+"</a>")&&jQuery("#page_meta").append("<a href='/sector/"+getURLSlug(a.sector).toLowerCase()+"' class='subsector_name'>"+a.sector+"</a>")}function show_loading(){$("#index").html("<div class='loading'>&nbsp;</div>")}
function hide_loading(){$("#index .loading").hide()}
function load_profile_info(){$.post("/feedback/index.php",{method:"get_user_attributes"},function(a){jQuery("#small_profile").show();if(typeof a.display_name!="undefined"&&a.display_name!=null){jQuery("#small_profile").append("<div id='small_profile_image'><a href='/profile/'><img src='http://www.gravatar.com/avatar/"+a.email_hash+"?s=42'></a></div><div><div id='small_profile_display_name'><a href='/profile/'>"+a.display_name+"</a></div></div>");jQuery.each(a,function(b,c){add_or_update_setting(b,
c)})}},dataType="json")}function clear_page(){jQuery("#right").html("<ul id='results'></ul>");jQuery("#main").html("")}
function load_current_page(){Buleys.view.type=="account"&&load_profile_info();if(Buleys.view.type!=="account"&&Buleys.view.type!=="home"&&Buleys.view.type!=="signin"&&Buleys.view.type!==""&&Buleys.view.type!=="start"&&Buleys.view.type!=="settings"&&Buleys.view.type!=="favorites"&&Buleys.view.type!=="read"&&Buleys.view.type!=="unread"&&Buleys.view.type!=="seen"&&Buleys.view.type!=="unseen"&&Buleys.view.type!=="unarchived"&&Buleys.view.type!=="archived"){get_page_follow_status(Buleys.view.type,Buleys.view.slug);
get_page_subscription_status(Buleys.view.type,Buleys.view.slug);get_page_topic_info(Buleys.view.type,Buleys.view.slug)}if(Buleys.view.type=="settings"||Buleys.view.type=="account")get_settings_page();else if(Buleys.view.type=="signin"||"signin"==Buleys.view.type||"start"==Buleys.view.type)Buleys.view.loaded!="signin"&&get_signin();else if(Buleys.view.type=="register")get_registration();else if(Buleys.view.type=="confirm")get_confirmation();else if(Buleys.view.type=="favorites"||Buleys.view.page==
"favorites"||Buleys.view.page=="favs")get_favorites(Buleys.view.type,Buleys.view.slug);else if(Buleys.view.type=="archive"||Buleys.view.page=="archive"||Buleys.view.page=="archived")get_archived(Buleys.view.type,Buleys.view.slug);else if(Buleys.view.type=="trash"||Buleys.view.page=="trash"||Buleys.view.page=="trashed"||Buleys.view.page=="deleted")get_deleted(Buleys.view.type,Buleys.view.slug);else if(Buleys.view.type=="read"||Buleys.view.page=="read")get_read(Buleys.view.type,Buleys.view.slug,null,
null,false);else if(Buleys.view.type=="unread"||Buleys.view.page=="unread")get_read(Buleys.view.type,Buleys.view.slug,null,null,true);else if(Buleys.view.type=="seen"||Buleys.view.page=="seen")get_seen(Buleys.view.type,Buleys.view.slug,null,null,false);else Buleys.view.type=="unseen"||Buleys.view.page=="unseen"?get_seen(Buleys.view.type,Buleys.view.slug,null,null,true):get_items(Buleys.view.type,Buleys.view.slug);Buleys.view.loaded=Buleys.view.type}
function reload_results(){clear_page();set_page_vars();load_current_page()}function set_page_vars(){console.log("Setting page vars: ",location.pathname);var a=location.pathname;a=a.replace(/^\//,"");a=a.replace(/\/$/,"");a=a.split("/");Buleys.view.type=a[0];Buleys.view.slug=a[1];Buleys.view.page=a[2]};
