function parse_single_topic(b){b.split("_");Buleys.queues.pending_crawls.slice(0,1);Buleys.queues.pending_crawls.push(b)}
function update_topic_in_topics_database(b,c){new_topics_transaction();c.topic_key=b;c.modified=new Date;if(typeof c.last_updated!="undefined")c.last_updated=new Date(parseInt(c.last_updated)*1E3);if(typeof c.updated!="undefined")c.updated=new Date(parseInt(c.updated)*1E3);if(typeof c.last_attempt!="undefined")c.last_attempt=new Date(parseInt(c.last_attempt)*1E3);var a=Buleys.objectStore.put(c);a.onsuccess=function(){Buleys.objectId=a.result};a.onerror=function(){}}
function get_page_topic_info(b,c){new_topics_transaction();var a=Buleys.objectStore.get(b+"_"+c);a.onsuccess=function(){if(!(typeof a.result=="undefined"||a.result=="")){if(typeof a.result.name!="undefined"){jQuery("#page_meta").append("<a href='/"+a.result.type+"/"+a.result.key+"' class='topic_name'>"+a.result.name+"</a>");window.document.title=window.document.title.replace(/[|\s]*?Buley's/,"");window.document.title=window.document.title+a.result.name+" | Buley's"}typeof a.result.subsector!="undefined"&&
jQuery("#page_meta").append("<a href='/sector/"+getURLSlug(a.result.subsector).toLowerCase()+"' class='sector_name'>"+a.result.subsector+"</a>");typeof a.result.sector!="undefined"&&jQuery("#page_meta").append("<a href='/sector/"+getURLSlug(a.result.sector).toLowerCase()+"' class='subsector_name'>"+a.result.sector+"</a>")}};a.onerror=function(){}}
function get_topics(){try{new_topics_transaction();Buleys.index=Buleys.objectStore.index("topic_key");var b=Buleys.index.getAll();b.onsuccess=function(){var a=b.result;a&&a.length>=0&&jQuery.each(a,function(){})};request.onerror=function(){}}catch(c){}}function remove_topic(b){new_topics_transaction();b=Buleys.objectStore["delete"](b);b.onsuccess=function(){delete Buleys.objectId};b.onerror=function(){}}
function add_or_update_topic(b,c){new_topics_transaction();if(typeof c=="undefined")c={};var a=Buleys.objectStore.get(b);a.onsuccess=function(){typeof a.result=="undefined"?add_topic_to_topics_database(b,c):update_topic_in_topics_database(b,c)};a.onerror=function(){}}
function add_topic_to_topics_database(b,c){new_topics_transaction();if(typeof c=="undefined")c={};c.topic_key=b;c.modified=new Date;var a=Buleys.objectStore.add(c);a.onsuccess=function(){Buleys.objectId=a.result};a.onerror=function(){}}
function new_topics_transaction(){try{var b=Buleys.db.transaction(["topic"],1,1E3);b.oncomplete=function(){delete Buleys.objectStore};b.onabort=function(){};Buleys.objectStore=b.objectStore("topic")}catch(c){b=Buleys.db.setVersion(parseInt(Buleys.db.version)+1);b.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("topic",{keyPath:"topic_key"},true);Buleys.objectStore.createIndex("slug","slug",{unique:false});Buleys.objectStore.createIndex("type","type",{unique:false});Buleys.objectStore.createIndex("last_updated",
"last_updated",{unique:false})};b.onerror=function(){}}};
