function new_deleted_transaction(){jQuery(document).trigger("new_deleted_transaction");try{var a=Buleys.db.transaction(["deleted"],IDBTransaction.READ_WRITE,1E3);a.oncomplete=function(){delete Buleys.objectStoreDeleted};a.onerror=function(){};a.onabort=function(){};Buleys.objectStoreDeleted=a.objectStore("deleted")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.version,10));a.onsuccess=function(){Buleys.objectStoreDeleted=Buleys.db.createObjectStore("deleted",{keyPath:"link"},true);Buleys.objectStoreDeleted.createIndex("topic_slug",
"topic_slug",{unique:false});Buleys.objectStoreDeleted.createIndex("topic_type","topic_type",{unique:false});Buleys.objectStoreDeleted.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function get_deleted(a,b,d,c,e){jQuery(document).trigger("get_deleted",{type_filter:a,slug_filter:b,begin_timeframe:d,end_timestamp:c,make_inverse:e});if(typeof e=="undefined")e=false;typeof d=="undefined"||d==null||parseInt(d);typeof c=="undefined"||c==null?(new Date).getTime():parseInt(c);new_categories_transaction();Buleys.indexCategoriesSlug=Buleys.objectStoreCategories.index("slug");try{var l=IDBKeyRange.lowerBound(b),i=Buleys.indexCategoriesSlug.openCursor(l)}catch(n){return}i.onsuccess=function(h){h=
h.target.result;var f=h.value;if(f){new_deleted_transaction();var j=Buleys.objectStoreDeleted.get(f.link);j.onsuccess=function(m){if(typeof m.target.result!=="undefined"&&e!==true){new_item_transaction();var g=Buleys.objectStore.get(f.link);g.onsuccess=function(k){typeof k.target.result!=="undefined"&&e!==true&&jQuery("#"+f.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item_raw_no_trash(k.target.result.link)}}else if(typeof j.result=="undefined"&&e==true){new_item_transaction();g=Buleys.objectStoreDeleted.get(f.link);
g.onsuccess=function(){typeof g.result!=="undefined"&&typeof g.result!=="undefined"&&jQuery("#"+f.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item_raw(g.result.link)}}};try{h["continue"]()}catch(o){f=false}}};i.onerror=function(){}}
function mark_item_as_deleted(a,b,d){jQuery(document).trigger("mark_item_as_deleted");new_deleted_transaction();a={link:a,topic_slug:b,topic_type:d,modified:(new Date).getTime()};var c=Buleys.objectStoreDeleted.add(a);c.onsuccess=function(){Buleys.objectId=c.result};c.onerror=function(){}}
function mark_item_as_undeleted(a){jQuery(document).trigger("mark_item_as_undeleted");new_deleted_transaction();a=Buleys.objectStoreDeleted["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function delete_item(a,b,d){jQuery(document).trigger("delete_item");new_deleted_transaction();var c={link:a,modified:(new Date).getTime()},e=Buleys.objectStoreDeleted.add(c);e.onsuccess=function(){Buleys.objectId=e.result;remove_item_from_favorites_database(a,b,d);remove_item_from_categories_database(a,b,d);remove_item_from_archives_database(a,b,d);remove_item_from_seens_database(a,b,d);remove_item_from_read_database(a,b,d)};e.onerror=function(){}}
function undelete_item(a,b,d){jQuery(document).trigger("undelete_item");console.log("UNDELETING ITEM!");console.log([a,b,d]);new_deleted_transaction();b=Buleys.objectStoreDeleted["delete"](a);b.onsuccess=function(c){Buleys.objectId=c.target.result;console.log(c.target.result);recreate_item(a)};b.onerror=function(){}}
function check_if_item_is_deleted(a){jQuery(document).trigger("check_if_item_is_deleted");jQuery("document").trigger("check_if_item_is_deleted",{item_url:a});new_deleted_transaction();var b=Buleys.objectStoreDeleted.get(a);b.onsuccess=function(){checker=b;if(typeof b.result!="undefined"){jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).prepend("<span class='delete_status'><a href='"+a+"' class='fav_link star_icon'></a></span>");jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("deleted")}else jQuery("#"+
a.replace(/[^a-zA-Z0-9-_]+/g,"")).prepend("<span class='delete_status'><a href='"+a+"' class='unfav_link empty_star_icon'></a></span>")};b.onerror=function(){}}function add_item_to_deletes_database(a,b,d){jQuery(document).trigger("add_item_to_deletes_database");new_deleted_transaction();a={item_link:a,topic_slug:b,topic_type:d,modified:(new Date).getTime()};var c=Buleys.objectStoreDeleted.add(a);c.onsuccess=function(){Buleys.objectId=c.result};c.onerror=function(){}}
function remove_item_from_deletes_database(a){jQuery(document).trigger("remove_item_from_deletes_database");new_deleted_transaction();a=Buleys.objectStoreDeleted["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}};
