function new_deleted_transaction(){try{var a=Buleys.db.transaction(["deleted"],1,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("deleted")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.db.version)+1);a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("deleted",{keyPath:"link"},true);Buleys.objectStore.createIndex("topic_slug","topic_slug",{unique:false});Buleys.objectStore.createIndex("topic_type","topic_type",{unique:false});
Buleys.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function get_deleted(a,b,c,d,e){if(typeof e=="undefined")e=false;typeof c=="undefined"||c==null||parseInt(c);typeof d=="undefined"||d==null?(new Date).getTime():parseInt(d);new_categories_transaction();Buleys.index=Buleys.objectStore.index("slug");var j=Buleys.index.getAll(b);j.onsuccess=function(){var g=j.result;if(g)g.length>1?jQuery.each(g,function(k,h){new_deleted_transaction();var i=Buleys.objectStore.get(h.link);i.onsuccess=function(){if(typeof i.result!=="undefined"&&e!==true){new_item_transaction();
var f=Buleys.objectStore.get(i.result.link);f.onsuccess=function(){typeof f.result!=="undefined"&&e!==true&&jQuery("#"+h.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item_raw_no_trash(f.result.link)}}else if(typeof i.result=="undefined"&&e==true){new_item_transaction();f=Buleys.objectStore.get(h.link);f.onsuccess=function(){typeof f.result!=="undefined"&&typeof f.result!=="undefined"&&jQuery("#"+h.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0&&get_item_raw(f.result.link)}}}}):get_item(g.link)};
j.onerror=function(){}}function mark_item_as_deleted(a,b,c){new_deleted_transaction();a={link:a,topic_slug:b,topic_type:c,modified:(new Date).getTime()};var d=Buleys.objectStore.add(a);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}function mark_item_as_undeleted(a){new_deleted_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function delete_item(a,b,c){new_deleted_transaction();var d={link:a,modified:(new Date).getTime()},e=Buleys.objectStore.add(d);e.onsuccess=function(){Buleys.objectId=e.result};e.onerror=function(){};remove_item_from_favorites_database(a,b,c);remove_item_from_categories_database(a,b,c);remove_item_from_archives_database(a,b,c);remove_item_from_seens_database(a,b,c);remove_item_from_read_database(a,b,c)}
function check_if_item_is_deleted(a){new_deleted_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){checker=b;if(typeof b.result!="undefined"){jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).prepend("<span class='delete_status'><a href='"+a+"' class='fav_link'><img src='http://buleys.com/images/icons/fugue-shadowless/star.png'></a></span>");jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("deleted")}else jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).prepend("<span class='delete_status'><a href='"+
a+"' class='unfav_link'><img src='http://buleys.com/images/icons/fugue-shadowless/star-empty.png'></a></span>")};b.onerror=function(){}}function add_item_to_deletes_database(a,b,c){new_deleted_transaction();a={item_link:a,topic_slug:b,topic_type:c,modified:(new Date).getTime()};var d=Buleys.objectStore.add(a);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}
function remove_item_from_deletes_database(a){new_deleted_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}};
