function new_votes_transaction(){try{var a=Buleys.db.transaction(["votes"],1,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("votes")}catch(c){a=Buleys.db.setVersion(parseInt(Buleys.db.version)+1);a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("votes",{keyPath:"vote_key"},false);Buleys.objectStore.createIndex("vote_value","vote_value",{unique:false});Buleys.objectStore.createIndex("modified","modified",{unique:false})};
a.onerror=function(){}}}
function check_item_vote_status_for_overlay(a){new_votes_transaction();var c=Buleys.objectStore.get(a.replace(/[^a-zA-Z0-9-_]+/g,""));c.onsuccess=function(b){checker=c;if(typeof b.target.result!=="undefined"){if(b.target.result.vote_value==-1)jQuery("#overlay_left").prepend('<div class="vote_context"><a href="#" class="vote_up" alt="'+Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'"><img src="/images/icons/fugue-shadowless/thumb-up-empty.png"/></a><br><a href="#" class="vote_down" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,
"")+'" link="'+a+'" alt="'+Buleys.view.slug+'" ><img src="/images/icons/fugue-shadowless/thumb.png"/></a></div>');else b.target.result.vote_value==1?jQuery("#overlay_left").prepend('<div class="vote_context"><a href="#" class="vote_up" alt="'+Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'"><img src="/images/icons/fugue-shadowless/thumb-up.png"/></a><br><a href="#" class="vote_down" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'" alt="'+
Buleys.view.slug+'" ><img src="/images/icons/fugue-shadowless/thumb-empty.png"/></a></div>'):jQuery("#overlay_left").prepend('<div class="vote_context"><a href="#" class="vote_up" alt="'+Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'"><img src="/images/icons/fugue-shadowless/thumb-up-empty.png"/></a><br><a href="#" class="vote_down" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'" alt="'+Buleys.view.slug+'" ><img src="/images/icons/fugue-shadowless/thumb-empty.png"/></a></div>');
jQuery("#overlay_left").parent().addClass("voted")}else{jQuery("#overlay_left").prepend('<div class="vote_context"><a href="#" class="vote_up" alt="'+Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'"><img src="/images/icons/fugue-shadowless/thumb-up-empty.png"/></a><br><a href="#" class="vote_down" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'" alt="'+Buleys.view.slug+'" ><img src="/images/icons/fugue-shadowless/thumb-empty.png"/></a></div>');
jQuery("#overlay_left").parent().addClass("unvoted")}};c.onerror=function(){}}function get_vote_info(a,c,b){new_votes_transaction();var d=a.replace(/[^a-zA-Z0-9-_]+/g,"")+c.toLowerCase()+b.toLowerCase(),e=Buleys.objectStore.get(d);e.onsuccess=function(){if(!(typeof e.result=="undefined"||e.result==""))if(typeof e.result!="undefined")if(e.result.vote_value==0)jQuery("#"+d).addClass("voted downvoted");else e.result.vote_value==1&&jQuery("#"+d).addClass("voted upvoted")};e.onerror=function(){}}
function get_votes(){try{new_votes_transaction();Buleys.index=Buleys.objectStore.index("vote_key");var a=Buleys.index.getAll();a.onsuccess=function(){var b=a.result;b&&b.length>=0&&jQuery.each(b,function(){})};request.onerror=function(){}}catch(c){}}function remove_vote(a){new_votes_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function add_or_update_vote(a,c){new_votes_transaction();if(typeof c=="undefined")c="";var b=Buleys.objectStore.get(a);b.onsuccess=function(){typeof b.result=="undefined"?add_vote_to_votes_database(a,c):update_vote_in_votes_database(a,c)};b.onerror=function(){}}function add_vote_to_votes_database(a,c){new_votes_transaction();var b={vote_key:a,vote_value:c,modified:(new Date).getTime()},d=Buleys.objectStore.add(b);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}
function update_vote_in_votes_database(a,c){new_votes_transaction();var b={vote_key:a,vote_value:c,modified:(new Date).getTime()},d=Buleys.objectStore.put(b);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}};
