function new_votes_transaction(){jQuery(document).trigger("new_votes_transaction");try{var a=Buleys.db.transaction(["votes"],IDBTransaction.READ_WRITE,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("votes")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.version,10));a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("votes",{keyPath:"vote_key"},false);Buleys.objectStore.createIndex("vote_value","vote_value",{unique:false});
Buleys.objectStore.createIndex("modified","modified",{unique:false})};a.onerror=function(){}}}
function check_item_vote_status_for_overlay(a){jQuery(document).trigger("check_item_vote_status_for_overlay");new_votes_transaction();var b=Buleys.objectStore.get(a.replace(/[^a-zA-Z0-9-_]+/g,""));b.onsuccess=function(c){checker=b;if(typeof c.target.result!=="undefined"){if(c.target.result.vote_value==-1)jQuery("#overlay_left").prepend('<div class="vote_context voted"><div class="vote_up empty_thumb_up_icon" alt="'+Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+
a+'"></div><div class="vote_down vote thumb_icon" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'" alt="'+Buleys.view.slug+'" ></div></div>');else c.target.result.vote_value==1?jQuery("#overlay_left").prepend('<div class="vote_context voted"><div class="vote_up vote thumb_up_icon" alt="'+Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'"></div><div class="vote_down empty_thumb_icon" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+
'" link="'+a+'" alt="'+Buleys.view.slug+'" ></div></div>'):jQuery("#overlay_left").prepend('<div class="vote_context"><div class="vote_up empty_thumb_up_icon" alt="'+Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'"></div><div href="#" class="vote_down empty_thumb_icon" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'" alt="'+Buleys.view.slug+'" ></div></div>');jQuery("#overlay_left").parent().addClass("voted")}else{jQuery("#overlay_left").prepend('<div class="vote_context"><div class="vote_up empty_thumb_up_icon" alt="'+
Buleys.view.slug+'" id="overlay_upvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'"></div><div href="#" class="vote_down empty_thumb_icon" id="overlay_downvote_'+a.replace(/[^a-zA-Z0-9-_]+/g,"")+'" link="'+a+'" alt="'+Buleys.view.slug+'" ></div></div>');jQuery("#overlay_left").parent().addClass("unvoted")}};b.onerror=function(){}}
function get_vote_info(a,b,c){jQuery(document).trigger("get_vote_info");new_votes_transaction();var d=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+c.toLowerCase(),e=Buleys.objectStore.get(d);e.onsuccess=function(){if(!(typeof e.result=="undefined"||e.result==""))if(typeof e.result!="undefined")if(e.result.vote_value==0)jQuery("#"+d).addClass("voted downvoted");else e.result.vote_value==1&&jQuery("#"+d).addClass("voted upvoted")};e.onerror=function(){}}
function get_votes(){jQuery(document).trigger("get_votes");try{new_votes_transaction();Buleys.index=Buleys.objectStore.index("vote_key");var a=Buleys.index.openCursor();a.onsuccess=function(){var c=a.result;c&&c.length>=0&&jQuery.each(c,function(){})};request.onerror=function(){}}catch(b){}}function remove_vote(a){jQuery(document).trigger("remove_vote");new_votes_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function add_or_update_vote(a,b){jQuery(document).trigger("add_or_update_vote");new_votes_transaction();if(typeof b=="undefined")b="";var c=Buleys.objectStore.get(a);c.onsuccess=function(){typeof c.result=="undefined"?add_vote_to_votes_database(a,b):update_vote_in_votes_database(a,b)};c.onerror=function(){}}
function add_vote_to_votes_database(a,b){jQuery(document).trigger("add_vote_to_votes_database");new_votes_transaction();var c={vote_key:a,vote_value:b,modified:(new Date).getTime()},d=Buleys.objectStore.add(c);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}
function update_vote_in_votes_database(a,b){jQuery(document).trigger("update_vote_in_votes_database");new_votes_transaction();var c={vote_key:a,vote_value:b,modified:(new Date).getTime()},d=Buleys.objectStore.put(c);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}
$(".vote_up").live("click",function(a){a.preventDefault();a=$(this).attr("link").replace(/[^a-zA-Z0-9-_]+/g,"");var b=a.replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery("#overlay_upvote_"+b).hasClass("vote")){jQuery("#overlay_upvote_"+b).removeClass("thumb_up_icon").addClass("empty_thumb_up_icon");$(".vote").removeClass("vote");$(this).parent().removeClass("voted");post_feedback("item_remove_upvote",a,Buleys.view.type,Buleys.view.slug);remove_vote(a)}else{jQuery("#overlay_downvote_"+b).removeClass("thumb_icon").addClass("empty_thumb_icon");
jQuery("#overlay_upvote_"+b).removeClass("empty_thumb_up_icon").addClass("thumb_up_icon");$(".vote").removeClass("vote");$(this).parent().addClass("voted");$(this).addClass("vote");post_feedback("item_upvote",a,Buleys.view.type,Buleys.view.slug);add_or_update_vote(a,1)}});
$(".vote_down").live("click",function(a){a.preventDefault();a=$(this).attr("link").replace(/[^a-zA-Z0-9-_]+/g,"");var b=a.replace(/[^a-zA-Z0-9-_]+/g,"");if(jQuery("#overlay_downvote_"+b).hasClass("vote")){jQuery("#overlay_downvote_"+b).removeClass("thumb_icon").addClass("empty_thumb_icon");$(".vote").removeClass("vote");$(this).parent().removeClass("voted");post_feedback("item_remove_downvote",a,Buleys.view.type,Buleys.view.slug);remove_vote(a)}else{jQuery("#overlay_downvote_"+b).removeClass("empty_thumb_icon").addClass("thumb_icon");
jQuery("#overlay_upvote_"+b).removeClass("thumb_up_icon").addClass("empty_thumb_up_icon");$(".vote").removeClass("vote");$(this).parent().addClass("voted");$(this).addClass("vote");post_feedback("item_downvote",a,Buleys.view.type,Buleys.view.slug);add_or_update_vote(a,-1)}});
