function new_categories_transaction(){jQuery(document).trigger("new_categories_transaction");try{var a=Buleys.db.transaction(["categories"],IDBTransaction.READ_WRITE,1E3);a.oncomplete=function(){delete Buleys.objectStoreCategories};a.onabort=function(){};Buleys.objectStoreCategories=a.objectStore("categories")}catch(b){a=Buleys.db.setVersion(Buleys.version);a.onsuccess=function(d){error_log(d);Buleys.objectStoreCategories=Buleys.db.createObjectStore("categories",{keyPath:"id"},true);Buleys.objectStoreCategories.createIndex("link",
"link",{unique:false});Buleys.objectStoreCategories.createIndex("slug","slug",{unique:false});Buleys.objectStoreCategories.createIndex("type","type",{unique:false});Buleys.objectStoreCategories.createIndex("modified","modified",{unique:false});d=Buleys.db.transaction(["categories"],IDBTransaction.READ_WRITE,1E3);d.oncomplete=function(){delete Buleys.objectStoreCategories};d.onabort=function(){};Buleys.objectStoreCategories=d.objectStore("categories")};a.onerror=function(){}}}
function add_category_controls(a){jQuery(document).trigger("add_category_controls");jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .delete_category").remove();jQuery("#overlay .selected_category").removeClass(".selected_category");var b,d=jQuery(a).html(),c=jQuery(a).attr("link"),f=jQuery(a).attr("type"),e=jQuery(a).attr("slug");new_votes_transaction();var h=c.replace(/[^a-zA-Z0-9-_]+/g,"")+f.toLowerCase()+e.toLowerCase(),g=Buleys.objectStore.get(h);
g.onsuccess=function(){if(typeof g.result=="undefined"||g.result==""){b="<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+c+"' type='"+f+"' slug='"+e+"'></span>";b=b+""+d;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>";b=b+"<div class='vote_down_category empty_thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>"}else if(typeof g.result!="undefined")if(g.result.vote_value==
-1){b="<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+c+"' type='"+f+"' slug='"+e+"'></span>";b=b+""+d;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>";b=b+"<div class='remove_category_down_vote thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>"}else{b=g.result.vote_value==1?"<span class='remove_category_up_vote thumb_up_icon float_left category_hover_icon ' link='"+
c+"' type='"+f+"' slug='"+e+"'></span>":"<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+c+"' type='"+f+"' slug='"+e+"'></span>";b=b+""+d;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>";b=b+"<div class='vote_down_category empty_thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>"}else{b="<span class='vote_up_category empty_thumb_up_icon float_left category_hover_icon ' link='"+
c+"' type='"+f+"' slug='"+e+"'></span>";b=b+""+d;b=b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>";b=b+"<div class='vote_down_category empty_thumb_icon float_right category_hover_icon' link='"+c+"' type='"+f+"' slug='"+e+"'></div>"}jQuery(a).html(b)};g.onerror=function(){}}
function remove_category_for_item(a,b,d){jQuery(document).trigger("remove_category_for_item");new_categories_transaction();a=Buleys.objectStoreCategories["delete"](a+d+b);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function add_category_controls_without_vote_status(a){jQuery(document).trigger("add_category_controls_without_vote_status");jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .delete_category").remove();jQuery("#overlay .selected_category").removeClass(".selected_category");var b=jQuery(a).html(),d=jQuery(a).attr("link"),c=jQuery(a).attr("type"),f=jQuery(a).attr("slug");jQuery(a).html("<div class='vote_block'>"+("<span class='vote_up_category thumb_up_icon float_left category_hover_icon ' link='"+
d+"' type='"+c+"' slug='"+f+"'></span>"+b+"<div class='delete_category float_right cross_icon category_hover_icon' link='"+d+"' type='"+c+"' slug='"+f+"'></div><div class='vote_down_category thumb_icon float_right category_hover_icon' link='"+d+"' type='"+c+"' slug='"+f+"'></div>")+"</div>")}
function remove_category_for_item(a,b,d){jQuery(document).trigger("remove_category_for_item");new_categories_transaction();a=Buleys.objectStoreCategories["delete"](a+d+b);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function remove_item_from_categories_database(a){jQuery(document).trigger("remove_item_from_categories_database");new_categories_transaction();Buleys.index=Buleys.objectStoreCategories.index("link");var b=Buleys.index.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined")if(typeof b.result!=="undefined"){var d="";d=b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")+b.result.slug.toLowerCase()+b.result.type.toLowerCase();new_categories_transaction();d=Buleys.objectStoreCategories["delete"](d);d.onsuccess=
function(){delete Buleys.objectId};d.onerror=function(){}}else $.each(b.result,function(c,f){var e="";e=f.link.replace(/[^a-zA-Z0-9-_]+/g,"")+f.slug.toLowerCase()+f.type.toLowerCase();new_categories_transaction();e=Buleys.objectStoreCategories["delete"](e);e.onsuccess=function(){delete Buleys.objectId};e.onerror=function(){}})};b.onerror=function(){}}
function add_categories_to_categories_database(a,b){jQuery(document).trigger("add_categories_to_categories_database");jQuery.each(b,function(d,c){if(typeof c.slug!=="undefined"){new_categories_transaction();var f={id:a.replace(/[^a-zA-Z0-9-_]+/g,"")+c.slug.toLowerCase()+c.type.toLowerCase(),link:a,slug:c.slug,type:c.type,value:c.display,modified:(new Date).getTime()};f=Buleys.objectStoreCategories.add(f);f.onsuccess=function(){if(typeof c.slug!=="undefined"){var e=c.type.toLowerCase()+"_"+c.slug.toLowerCase();
if(typeof Buleys.queues.new_items[e]=="undefined")Buleys.queues.new_items[e]=0;Buleys.queues.new_items[e]+=1}};f.onerror=function(){}}})}
function get_item_categories_for_overlay(a){jQuery(document).trigger("get_item_categories_for_overlay");new_categories_transaction();Buleys.objectStoreCategories.get(a);try{new_categories_transaction();Buleys.index=Buleys.objectStoreCategories.index("link");var b=Buleys.index.openCursor(a);b.onsuccess=function(){var c=b.result;c&&c.length>=0&&jQuery.each(c,function(f,e){if(jQuery("#categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).length<1){var h="<ul class='category_list' id='categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,
"")+"'></ul>";jQuery("#overlay_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).append(h)}h="<li id='list_item_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+e.type.toLowerCase()+e.slug.toLowerCase()+"' class='category_list_item' link='"+a+"' type='"+e.type.toLowerCase()+"' slug='"+e.slug.toLowerCase()+"'><a id='"+a.replace(/[^a-zA-Z0-9-_]+/g,"")+e.type.toLowerCase()+e.slug.toLowerCase()+"'  class='category' link='"+a+"' type='"+e.type.toLowerCase()+"' slug='"+e.slug.toLowerCase()+"' href='/"+e.type.toLowerCase()+"/"+e.slug+
"'>"+e.value+"</a></li>";jQuery("#categories_"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).append(h);get_vote_info(a,e.type.toLowerCase(),e.slug.toLowerCase())})};request.onerror=function(){}}catch(d){}}$(".delete_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),d=$(this).attr("slug");$(this).parent().parent().remove();remove_category_for_item(a.replace(/[^a-zA-Z0-9-_]+/g,""),b,d);$(this).hasClass("voted")||post_feedback("delete_category",a,b,d)});
$(".vote_up_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),d=$(this).attr("slug"),c="";c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+d.toLowerCase();jQuery(this).removeClass("empty_thumb_up_icon").addClass("thumb_up_icon");jQuery(this).parent().children(".thumb_icon").removeClass(".thumb_icon").addClass("empty_thumb_icon");add_or_update_vote(c,1);$(this).hasClass("voted")||post_feedback("category_upvote",a,b,d);$(this).addClass("voted");
$(this).removeClass("vote_up_category");$(this).addClass("remove_category_up_vote")});
$(".vote_down_category").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),d=$(this).attr("slug"),c="";jQuery(this).removeClass("empty_thumb_icon").addClass("thumb_icon");jQuery(this).parent().children(".thumb_up_icon").removeClass(".thumb_up_icon").addClass("empty_thumb_up_icon");c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+d.toLowerCase();add_or_update_vote(c,-1);$(this).hasClass("voted")||post_feedback("category_downvote",a,b,d);$(this).addClass("voted");
$(this).removeClass("vote_down_category");$(this).addClass("remove_category_down_vote")});
$(".remove_category_up_vote").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),d=$(this).attr("slug"),c="";c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+d.toLowerCase();jQuery(this).removeClass("thumb_up_icon").addClass("empty_thumb_up_icon");remove_vote(c);$(this).hasClass("voted")&&post_feedback("remove_category_upvote",a,b,d);$(this).removeClass("voted");$(this).removeClass("remove_category_up_vote");$(this).addClass("vote_up_category")});
$(".remove_category_down_vote").live("click",function(a){a.preventDefault();a=$(this).attr("link");var b=$(this).attr("type"),d=$(this).attr("slug"),c="";jQuery(this).removeClass("thumb_icon").addClass("empty_thumb_icon");c=a.replace(/[^a-zA-Z0-9-_]+/g,"")+b.toLowerCase()+d.toLowerCase();remove_vote(c);$(this).hasClass("voted")&&post_feedback("remove_category_downvote",a,b,d);$(this).removeClass("voted");$(this).removeClass("remove_category_down_vote");$(this).addClass("vote_down_category")});
$("#overlay .category").live("mouseenter",function(a){a.preventDefault();add_category_controls(jQuery(this))});$("#overlay .category").live("mouseleave",function(a){a.preventDefault();jQuery("#overlay .vote_up_category").remove();jQuery("#overlay .vote_down_category").remove();jQuery("#overlay .remove_category_up_vote").remove();jQuery("#overlay .remove_category_down_vote").remove();jQuery("#overlay .delete_category").remove()});
