function new_follows_transaction(){jQuery(document).trigger("new_follows_transaction");try{var a=Buleys.db.transaction(["follows"],IDBTransaction.READ_WRITE,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("follows")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.version,10));a.onsuccess=function(){Buleys.objectStore=Buleys.db.createObjectStore("follows",{keyPath:"key"},true);Buleys.objectStore.createIndex("modified","modified",{unique:false});
var c=Buleys.db.transaction(["follows"],IDBTransaction.READ_WRITE,1E3);c.oncomplete=function(){delete Buleys.objectStore};c.onabort=function(){};Buleys.objectStore=c.objectStore("follows")};a.onerror=function(){}}}
function get_follows(){jQuery(document).trigger("get_follows");try{new_follows_transaction();Buleys.index=Buleys.objectStore;var a=Buleys.index.openCursor();a.onsuccess=function(){var c=a.result;c&&c.length>=0&&jQuery.each(c,function(d,e){parse_single_topic(e.key)})};request.onerror=function(){}}catch(b){}}$("html").bind("mousemove",function(a){Buleys.mouse.mouse_x=a.pageX;Buleys.mouse.mouse_y=a.pageY});
function getKeys(a){jQuery(document).trigger("getKeys");var b=[];if(typeof a!=="undefined"){$.each(a,function(c){b.push(c)});return b.length}else return 0}
function get_follows_deleteme(){jQuery(document).trigger("get_follows_deleteme");new_follows_transaction();try{new_categories_transaction();Buleys.index=Buleys.objectStoreCategories.index("id");var a=Buleys.index.openCursor();a.onsuccess=function(){var c=a.result;c&&c.length>=0&&jQuery.each(c,function(d,e){send_to_console("get_follows(): "+e)})};request.onerror=function(){}}catch(b){}}
function get_page_follow_status(a,b){jQuery(document).trigger("get_page_follow_status");InDB.new_transaction("follows",IDBTransaction.READ_WRITE,function(){console.log("follow transaction completed")},function(){console.log("follow transaction errored")},function(){console.log("follow transaction aborted")});var c=follows_transaction.get(a+"_"+b);c.onsuccess=function(){typeof c.result=="undefined"||c.result==""?jQuery("#page_follow_status").html("<div class='follow_topic empty_heart_icon'></div>"):
jQuery("#page_follow_status").html("<div class='unfollow_topic heart_icon'></div>")};c.onerror=function(){}}function remove_follow(a,b){jQuery(document).trigger("remove_follow");if(typeof a!=="undefined"&&typeof b!=="undefined"){new_follows_transaction();var c=Buleys.objectStore["delete"](a+"_"+b);c.onsuccess=function(){delete Buleys.objectId};c.onerror=function(){}}}
function add_follow_if_doesnt_exist(a,b){jQuery(document).trigger("add_follow_if_doesnt_exist");if(typeof a!=="undefined"&&typeof b!=="undefined"){new_follows_transaction();var c=Buleys.objectStore.get(a+"_"+b);c.onsuccess=function(){typeof c.result=="undefined"&&add_follow_to_follows_database(a,b)};c.onerror=function(){}}}
function add_follow_to_follows_database(a,b){jQuery(document).trigger("add_follow_to_follows_database");new_follows_transaction();var c={key:a+"_"+b,modified:(new Date).getTime()},d=Buleys.objectStore.add(c);d.onsuccess=function(){Buleys.objectId=d.result};d.onerror=function(){}}
$(".follow_topic").live("click",function(a){a.preventDefault();a=$(this).attr("key");var b=$(this).attr("type");if(typeof a=="undefined")a=Buleys.view.slug;if(typeof b=="undefined"||b=="")b=Buleys.view.type;add_follow_if_doesnt_exist(b,a);post_feedback("follow","",a,b);$(this).removeClass("empty_heart_icon").addClass("heart_icon");$(this).removeClass("follow_topic");$(this).addClass("unfollow_topic")});
$(".unfollow_topic").live("click",function(a){a.preventDefault();a=$(this).attr("key");var b=$(this).attr("type");if(typeof a=="undefined")a=Buleys.view.slug;if(typeof b=="undefined"||b=="")b=Buleys.view.type;remove_follow(b,a);post_feedback("unfollow","",a,b);$(this).removeClass("heart_icon").addClass("empty_heart_icon");$(this).removeClass("unfollow_topic");$(this).addClass("follow_topic")});
