function temporarily_disable_hotkeys(){jQuery(document).trigger("temporarily_disable_hotkeys")}function disable_hotkeys(){jQuery(document).trigger("disable_hotkeys");console.log("Disabling hotkeys");console.log(Buleys.settings);Buleys.settings.hotkeys.disabled=true}function enable_hotkeys(){jQuery(document).trigger("enable_hotkeys");delete Buleys.settings.hotkeys.disabled}$(document).bind("show_commands",function(a){a.preventDefault();$("#result_controls").show()});
$(document).bind("hide_commands",function(a){a.preventDefault();$("#result_controls").hide()});$(document).bind("show_button",function(){send_notification_to_desktop()});
$("html").live("keyup",function(a){console.log("disabled?");console.log(Buleys.settings.hotkeys.disabled);if(typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled==="undefined"||typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled!=="undefined"&&Buleys.settings.hotkeys.disabled!==true)if(a.keyCode==68)Buleys.shortcuts.d_depressed=false;else if(a.keyCode==83)Buleys.shortcuts.s_depressed=
false;else if(a.keyCode==16)Buleys.shortcuts.shift_depressed=false;else if(a.keyCode==72)Buleys.shortcuts.s_depressed||Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$(document).trigger("view_index"):$(document).trigger("close_item_preview"));else if(a.keyCode==76){if(!Buleys.shortcuts.s_depressed)if(!Buleys.shortcuts.d_depressed)if(Buleys.shortcuts.shift_depressed)$(document).trigger("view_home");else{$(document).trigger("preview_item");jQuery(".cursor")}}else if(a.keyCode==78){$(document).trigger("preview_item");
jQuery(".selected").length>0?jQuery("#results li.selected:first").addClass("cursor"):jQuery("#results li:first").addClass("cursor")}else if(a.keyCode==74)if(jQuery(".cursor").next().length>0)jQuery(".cursor").removeClass("cursor").next().addClass("cursor");else{jQuery(".cursor").removeClass("cursor");jQuery("#results li:first").addClass("cursor")}else if(a.keyCode==75)if(jQuery(".cursor").prev().length>0)jQuery(".cursor").removeClass("cursor").prev().addClass("cursor");else{jQuery(".cursor").removeClass("cursor");
jQuery("#results li:last").addClass("cursor")}else if(a.keyCode==27){jQuery(".cursor").removeClass("cursor");$(document).trigger("close_all")}else if(a.keyCode==77)jQuery(".cursor").removeClass("cursor");else if(a.keyCode==219)$(document).trigger("preview_item");else if(a.keyCode==221)$(document).trigger("close_item_preview");else if(a.keyCode==89)$(document).trigger("show_commands");else if(a.keyCode==85)$(document).trigger("hide_commands");else if(a.keyCode==65)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_all");
else Buleys.shortcuts.d_depressed&&$(document).trigger("select_none");else if(a.keyCode==82)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_unread");else if(Buleys.shortcuts.d_depressed)$(document).trigger("deselect_unread");else Buleys.shortcuts.shift_depressed?$(document).trigger("view_unread"):$(document).trigger("mark_unread");else if(a.keyCode!=13)if(a.keyCode==73)$(document).trigger("select");else if(a.keyCode==79)$(document).trigger("deselect");else if(a.keyCode==69)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_read");
else if(Buleys.shortcuts.d_depressed)$(document).trigger("deselect_read");else Buleys.shortcuts.shift_depressed?$(document).trigger("view_read"):$(document).trigger("mark_read");else if(a.keyCode==88)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_none");else Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$(document).trigger("view_trash"):$(document).trigger("delete"));else if(a.keyCode==67)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_archived");else if(Buleys.shortcuts.d_depressed)$(document).trigger("deselect_archived");
else Buleys.shortcuts.shift_depressed?$(document).trigger("view_archive"):$(document).trigger("archive");else if(a.keyCode==86)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_unarchived");else Buleys.shortcuts.d_depressed?$(document).trigger("deselect_unarchived"):$(document).trigger("unarchive");else if(a.keyCode==70)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_favorites");else if(Buleys.shortcuts.d_depressed)$(document).trigger("deselect_favorites");else Buleys.shortcuts.shift_depressed?
$(document).trigger("view_favorites"):$(document).trigger("favorite");else if(a.keyCode==71)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_unfavorite");else Buleys.shortcuts.d_depressed?$(document).trigger("deselect_unfavorite"):$(document).trigger("unfavorite");else if(a.keyCode==81)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_seen");else if(Buleys.shortcuts.d_depressed)$(document).trigger("deselect_seen");else Buleys.shortcuts.shift_depressed?$(document).trigger("view_seen"):
$(document).trigger("mark_seen");else if(a.keyCode==87)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_unseen");else if(Buleys.shortcuts.d_depressed)$(document).trigger("deselect_unseen");else Buleys.shortcuts.shift_depressed?$(document).trigger("view_unseen"):$(document).trigger("mark_unseen");else if(a.keyCode==90)if(Buleys.shortcuts.s_depressed)$(document).trigger("select_inverse");else Buleys.shortcuts.d_depressed||(Buleys.shortcuts.shift_depressed?$(document).trigger("view_index"):
$(document).trigger("undelete"));else if(a.keyCode==73)$(document).trigger("deselect");else a.keyCode==79&&$(document).trigger("select")});
$("html").live("keydown",function(a){if(typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled==="undefined"||typeof Buleys.settings!=="undefined"&&typeof Buleys.settings.hotkeys!=="undefined"&&typeof Buleys.settings.hotkeys.disabled!=="undefined"&&Buleys.settings.hotkeys.disabled!==true)if(a.keyCode==68)Buleys.shortcuts.d_depressed=true;else if(a.keyCode==83)Buleys.shortcuts.s_depressed=true;else if(a.keyCode==16)Buleys.shortcuts.shift_depressed=
true});
