jQuery(".item").live("click",function(){jQuery(this).addClass("selected");jQuery(this).trigger("preview_item")});
function new_item_transaction(){jQuery(document).trigger("new_item_transaction");try{var a=Buleys.db.transaction(["items"],IDBTransaction.READ_WRITE,1E3);a.oncomplete=function(){delete Buleys.objectStore};a.onabort=function(){};Buleys.objectStore=a.objectStore("items")}catch(b){a=Buleys.db.setVersion(parseInt(Buleys.version,10));a.onsuccess=function(){Buleys.db.objectStore=Buleys.db.createObjectStore("items",{keyPath:"link"},false);Buleys.db.objectStore.createIndex("author","author",{unique:false});
Buleys.db.objectStore.createIndex("published_date","published_date",{unique:false});Buleys.db.objectStore.createIndex("index_date","index_date",{unique:false});Buleys.db.objectStore.createIndex("modified","modified",{unique:false});var c=Buleys.db.transaction(["items"],IDBTransaction.READ_WRITE,1E3);c.oncomplete=function(){delete Buleys.objectStore};c.onabort=function(){};Buleys.objectStore=c.objectStore("items")};a.onerror=function(){}}}
function remove_item_from_items_database(a){jQuery(document).trigger("remove_item_from_items_database");new_item_transaction();a=Buleys.objectStore["delete"](a);a.onsuccess=function(){delete Buleys.objectId};a.onerror=function(){}}
function get_data_object_for_item(a){jQuery(document).trigger("get_data_object_for_item");return{link:a.link,title:a.title,author:a.author,entities:a.entities,published_date:(new Date(a.published_date)).getTime(),index_date:(new Date(a.index_date)).getTime(),modified:(new Date).getTime()}}
function add_item_to_results(a){jQuery(document).trigger("add_item_to_results");var b=a.link.replace(/[^a-zA-Z0-9-_]+/g,"");jQuery("#"+b).length||jQuery("<li class='item' modified= '"+a.modified+"'  index-date= '"+a.index_date+"' published-date= '"+a.published_date+"' id='"+a.link.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+a.link+"'>"+a.title+"</a><a class='examine_item magnify_icon' href='#'></a></li>").hide().appendTo("#results").fadeIn("slow")}
function prepend_item_to_results(a){jQuery(document).trigger("prepend_item_to_results");var b=a.link.replace(/[^a-zA-Z0-9-_]+/g,"");jQuery("#"+b).length||jQuery("<li class='item' modified= '"+a.modified+"'  index-date= '"+a.index_date+"' published-date= '"+a.published_date+"' id='"+a.link.replace(/[^a-zA-Z0-9-_]+/g,"")+"'><a href='"+a.link+"'>"+a.title+"</a><a class='examine_item magnify_icon' href='#'></a></li>").hide().prependTo("#results").fadeIn("slow")}
function add_item_to_items_database(a){jQuery(document).trigger("add_item_to_items_database");jQuery(document).trigger("add_item_to_items_database");var b=get_data_object_for_item(a);new_deleted_transaction();var c=Buleys.objectStoreDeleted.get(a.link);c.onsuccess=function(){if(typeof c.result==="undefined"){new_item_transaction();console.log("adding data");console.log(b);console.log("item");console.log(a);var d=Buleys.objectStore.add(b);d.onsuccess=function(f){console.log(f);if(a.entities.length>
1&&typeof a.entities.type==="undefined"&&typeof a.entities.slug==="undefined"){console.log(a.entities);console.log("^ item cats");$.each(a.entities,function(g,e){if(Buleys.view.type==="home"||typeof Buleys.view.slug==="undefined"||typeof Buleys.view.slug===""||e.slug!==null&&typeof e.slug!=="null")if(typeof page==="undefined"||page!=="favorites"&&page!=="seen"&&page!=="read"&&page!=="archive"&&page!=="trash")prepend_item_to_results(get_data_object_for_item(a))})}else if(a.entities.length===1&&typeof a.entities.slug!==
"undefined")if(Buleys.view.type==="home"||a.entities[0].slug.toLowerCase()===slug&&a.categories[0].type.toLowerCase()===type)add_item_to_results(get_data_object_for_item(a))};d.onerror=function(){}}};c.onerror=function(){}}
function check_if_item_is_read(a){jQuery(document).trigger("check_if_item_is_read");new_status_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){typeof b.result!=="undefined"?jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("read"):jQuery("#"+a.replace(/[^a-zA-Z0-9-_]+/g,"")).addClass("unread")};b.onerror=function(){}}
function recreate_item(a){jQuery(document).trigger("recreate_item",{item_url:a});if(typeof a!=="undefined"){new_item_transaction();a=Buleys.objectStore.get(a);a.onsuccess=function(b){if(typeof b.target.result!=="undefined"){var c=b.target.result;console.log("CREATE");console.log(b.target.result);add_categories_to_categories_database(c.link,c.entities);for(category in c.entities)if(c.entities.hasOwnProperty(category)){console.log(category);mark_item_as_seen(c.link,category.slug,category.type)}}};a.onerror=
function(){}}}
function get_item_raw_no_trash(a){jQuery(document).trigger("get_item_raw_no_trash");if(typeof a!=="undefined"){new_item_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined")if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(b.result);check_if_item_is_favorited(b.result.link);check_if_item_is_read(b.result.link);check_if_item_is_seen(b.result.link)}};b.onerror=function(){if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=
0){add_item_to_results(b.result);check_if_item_is_favorited(b.result.link);check_if_item_is_read(b.result.link);check_if_item_is_seen(b.result.link)}}}}
function get_item(a){jQuery(document).trigger("get_item");if(typeof a!=="undefined"){new_deleted_transaction();var b=Buleys.objectStoreDeleted.get(a);b.onsuccess=function(){if(typeof b.result==="undefined"){new_item_transaction();var c=Buleys.objectStore.get(a);c.onsuccess=function(){if(typeof c.result!=="undefined"){new_archived_transaction();var d=Buleys.objectStore.get(a);d.onsuccess=function(){typeof d.result==="undefined"&&get_item_raw_no_trash(c.result.link)};d.onerror=function(){if(jQuery("#"+
c.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(c.result);check_if_item_is_favorited(c.result.link);check_if_item_is_read(c.result.link);check_if_item_is_seen(c.result.link)}}}};c.onerror=function(){}}};b.onerror=function(){}}}
function get_item_raw(a){jQuery(document).trigger("get_item_raw");if(typeof a!=="undefined"){new_item_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined"){new_deleted_transaction();var c=Buleys.objectStoreDeleted.get(a);c.onsuccess=function(){if(typeof c.result==="undefined")if(jQuery("#"+b.result.link.replace(/[^a-zA-Z0-9-_]+/g,"")).length<=0){add_item_to_results(b.result);check_if_item_is_favorited(b.result.link);check_if_item_is_read(b.result.link);
check_if_item_is_seen(b.result.link)}}}};b.onerror=function(){}}}
function get_items(a,b,c,d){jQuery(document).trigger("get_items");console.log("inside get_items()");if(typeof make_inverse=="undefined")make_inverse=false;typeof c=="undefined"||c==null||parseInt(c);typeof d=="undefined"||d==null?(new Date).getTime():parseInt(d);new_categories_transaction();Buleys.indexCategoriesSlug=Buleys.objectStoreCategories.index("slug");try{var f=IDBKeyRange.only(b),g=Buleys.indexCategoriesSlug.openCursor(f)}catch(e){return}g.onsuccess=function(h){console.log(h.target.result);
console.log("successsssss");var i=h.target.result;(h=h.target.result.value)&&get_item(h.link);i["continue"]()}}
function index_items_by_field(a,b,c){jQuery(document).trigger("get_items");if(typeof Buleys.index_view=="undefined")Buleys.index_view={};if(typeof Buleys.index_view[c]==="undefined")Buleys.index_view[c]={};console.log("inside get_items()");if(typeof make_inverse=="undefined")make_inverse=false;typeof begin_timeframe=="undefined"||begin_timeframe==null||parseInt(begin_timeframe);typeof end_timeframe=="undefined"||end_timeframe==null?(new Date).getTime():parseInt(end_timeframe);new_categories_transaction();
Buleys.indexCategoriesSlug=Buleys.objectStoreCategories.index("slug");try{var d=IDBKeyRange.only(b),f=Buleys.indexCategoriesSlug.openCursor(d)}catch(g){return}if(undefined==typeof c)c="modified";f.onsuccess=function(e){console.log("successsssss");console.log(e);var h=e.target.result;e=e.target.result.value;console.log("#^^^^^");if(e)index_view[c][e[c]]=e.link;h["continue"]()}}
function get_item_for_console(a){jQuery(document).trigger("get_item_for_console");new_item_transaction();var b=Buleys.objectStore.get(a);b.onsuccess=function(){if(typeof b.result!=="undefined"&&typeof b.result.id==="string"){var c="<div id='console_"+b.result.id.replace(/[^a-zA-Z0-9-_]+/g,"")+"'>";c=c+"<h3><a href='"+b.result.id+"'>"+b.result.title+"</a></h3>";c=c+"<p>"+b.result.author+"</p>";c+="</div>";send_to_console(c)}};b.onerror=function(){}}
function fire_off_request(){jQuery(document).trigger("fire_off_request");$.ajax({url:typeof Buleys.view.type==="undefined"||Buleys.view.type===""?"http://api.buleys.com/feedback/":"http://cdn.buleys.com/js/collections/"+Buleys.view.type+"/"+Buleys.view.slug+".js",dataType:"jsonp",jsonpCallback:"load_collection",error:function(){$("#index").html("<li class='item'>No results.</li>")},success:function(a){Buleys.view.slug=a.info.key;Buleys.view.type=a.info.type;add_items(a.items,a.info.type,a.info.key);
load_page_title_info(a.info);add_or_update_topic(a.info.type+"_"+a.info.key,a.info)}})}function get_data_for_items(a){jQuery(document).trigger("get_data_for_items");$.each(a,function(b,c){get_item(c.link)})}function add_items(a,b,c){jQuery(document).trigger("add_items");$.each(a,function(d,f){add_item_if_new(f,b,c)})}function populate_and_maybe_setup_indexeddbs(a){jQuery(document).trigger("populate_and_maybe_setup_indexeddbs");$.each(a,function(b,c){add_item_if_doesnt_exist(c)})}
function add_item_if_new(a,b,c){jQuery(document).trigger("add_item_if_new");if(a.link){new_item_transaction();var d=Buleys.objectStore.get(a.link);d.onsuccess=function(f){if(typeof f.target.result==="undefined"){new_deleted_transaction();Buleys.objectStoreDeleted.get(a.link).onsuccess=function(g){if(typeof g.target.result==="undefined"){add_item_to_items_database(a);add_categories_to_categories_database(a.link,a.entities);send_to_console("<p>Added: <a href='"+a.link+"'>"+a.title+"</a></p>");g=b.toLowerCase()+
"_"+c.toLowerCase();if(typeof Buleys.queues.new_items[g]==="undefined")Buleys.queues.new_items[g]=0;Buleys.queues.new_items[g]+=1}};d.onerror=function(){}}};d.onerror=function(){}}}
function add_item_if_doesnt_exist_old(a){jQuery(document).trigger("add_item_if_doesnt_exist_old");new_item_transaction();var b=Buleys.objectStore.get(a.link);b.onsuccess=function(){if(typeof b.result==="undefined"){add_item_to_items_database(a);add_categories_to_categories_database(a.link,a.entities)}};b.onerror=function(){}}
function add_item_if_doesnt_exist(a){jQuery(document).trigger("add_item_if_doesnt_exist");new_item_transaction();var b=Buleys.objectStore.get(a.link);b.onsuccess=function(){if(typeof b.result==="undefined"){add_item_to_items_database(a);add_categories_to_categories_database(a.link,a.entities);a.categories.length>0&&$.each(a.categories,function(c,d){if(Buleys.view.type==="home"||typeof Buleys.view.slug==="undefined"||typeof Buleys.view.slug===""||d.key!==null&&typeof d.key!=="null"&&d.key===Buleys.view.slug&&
d.type===Buleys.view.type){add_item_to_results(get_data_object_for_item(a));check_if_item_is_favorited(a.link);check_if_item_is_read(a.link);check_if_item_is_seen(a.link)}})}};b.onerror=function(){}};
