$("body").bind("favorite",function(b){b.preventDefault();if(is_in_cursor_mode()){jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("unfav_link");
jQuery("#favorite_"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(".cursor a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(".cursor a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",$(".cursor a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item favorited</p>");
setTimeout("fade_console_message()",1E3)}else $.each($(".selected"),function(c,a){jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("empty_star_icon").addClass("star_icon");jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,
"")).children(".favorite_status").children("div").removeClass("unfav_link");jQuery("#favorite_"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("empty_star_icon").addClass("star_icon");jQuery("#favorite_"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".fav_link").removeClass("fav_link").addClass("unfav_link");add_item_to_favorites_database($(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("star",
$(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item favorited</p>");setTimeout("fade_console_message()",1E3)})});
$("body").bind("favorite",function(b){b.preventDefault();if(is_in_cursor_mode()){jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("star_icon").addClass("empty_star_icon");jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("unfav_link");
jQuery("#favorite_"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+jQuery(".cursor > a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");remove_item_from_favorites_database($(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);post_feedback("unstar",$(".cursor > a").attr("href"),Buleys.view.slug,Buleys.view.type);
send_to_console("<p>item removed from favorites</p>");setTimeout("fade_console_message()",1E3)}else $.each($(".selected"),function(c,a){jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").children("div").removeClass("star_icon").addClass("empty_star_icon");jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".favorite_status").parent().removeClass("unfavorited").addClass("favorited");jQuery("#"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,
"")).children(".favorite_status").children("div").removeClass("unfav_link");jQuery("#favorite_"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("star_icon").addClass("empty_star_icon");jQuery("#favorite_"+jQuery(a).children("a").attr("href").replace(/[^a-zA-Z0-9-_]+/g,"")).children(".unfav_link").removeClass("unfav_link").addClass("fav_link");remove_item_from_favorites_database($(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);
post_feedback("unstar",$(a).children("a").attr("href"),Buleys.view.slug,Buleys.view.type);send_to_console("<p>item removed from favorites</p>");setTimeout("fade_console_message()",1E3)})});
